import {NextResponse} from 'next/server';
import {getDB} from '@/lib/db';
import {requireOrganizationRole} from '@/lib/auth';

async function org(){const auth=await requireOrganizationRole('ORG_ADMIN');return auth.organizationId!}
function denied(e:unknown){return e instanceof Error&&e.message==='UNAUTHORIZED'?NextResponse.json({error:'Non autorisé'},{status:401}):NextResponse.json({error:'Erreur serveur'},{status:500})}
const accessible=`(t.organization_id=? OR EXISTS (SELECT 1 FROM organization_trainings ot WHERE ot.organization_id=? AND ot.training_id=t.id AND ot.status='ACTIVE'))`;
export async function GET(){try{const ORG=await org();const db=getDB();const [sessions,trainings,cohorts,trainers]=await Promise.all([db.prepare(`SELECT cs.id,cs.title,cs.training_id trainingId,cs.cohort_id cohortId,cs.trainer_user_id trainerUserId,cs.delivery_mode deliveryMode,cs.status,cs.starts_at startsAt,cs.ends_at endsAt,t.title trainingTitle,c.name cohortName,u.display_name trainerName FROM course_sessions cs JOIN trainings t ON t.id=cs.training_id LEFT JOIN cohorts c ON c.id=cs.cohort_id AND c.organization_id=cs.organization_id LEFT JOIN users u ON u.id=cs.trainer_user_id WHERE cs.organization_id=? ORDER BY CASE WHEN cs.starts_at IS NULL THEN 1 ELSE 0 END,cs.starts_at`).bind(ORG).all(),db.prepare(`SELECT t.id,t.slug,t.title,CASE WHEN t.organization_id=? THEN 'OWNED' ELSE 'ASSIGNED' END accessType FROM trainings t WHERE ${accessible} ORDER BY t.title`).bind(ORG,ORG,ORG).all(),db.prepare(`SELECT id,name,training_id trainingId,status FROM cohorts WHERE organization_id=? AND status!='ARCHIVED' ORDER BY name`).bind(ORG).all(),db.prepare(`SELECT u.id,u.display_name displayName,u.email FROM organization_members m JOIN users u ON u.id=m.user_id WHERE m.organization_id=? AND m.role='TRAINER' AND m.status='ACTIVE' ORDER BY u.display_name`).bind(ORG).all()]);return NextResponse.json({sessions:sessions.results||[],trainings:trainings.results||[],cohorts:cohorts.results||[],trainers:trainers.results||[]})}catch(e){return denied(e)}}
export async function POST(req:Request){try{const ORG=await org();const b=await req.json();const trainingId=Number(b.trainingId);if(!trainingId||!b.startsAt)return NextResponse.json({error:'Formation et date requises'},{status:400});const db=getDB();const training=await db.prepare(`SELECT t.id,t.title FROM trainings t WHERE t.id=? AND ${accessible}`).bind(trainingId,ORG,ORG).first<{id:number,title:string}>();if(!training)return NextResponse.json({error:'Formation introuvable'},{status:404});const trainerId=b.trainerUserId?Number(b.trainerUserId):null;if(trainerId){const member=await db.prepare("SELECT 1 ok FROM organization_members WHERE organization_id=? AND user_id=? AND role='TRAINER' AND status='ACTIVE'").bind(ORG,trainerId).first();if(!member)return NextResponse.json({error:'Formateur introuvable'},{status:404})}const cohortId=b.cohortId?Number(b.cohortId):null;if(cohortId){const cohort=await db.prepare('SELECT 1 ok FROM cohorts WHERE id=? AND organization_id=? AND training_id=?').bind(cohortId,ORG,trainingId).first();if(!cohort)return NextResponse.json({error:'Groupe introuvable'},{status:404})}const startsAt=String(b.startsAt);const endsAt=b.endsAt?String(b.endsAt):startsAt;if(trainerId){const conflict=await db.prepare(`SELECT id,title,starts_at startsAt,ends_at endsAt FROM course_sessions WHERE organization_id=? AND trainer_user_id=? AND status NOT IN ('CANCELLED','COMPLETED') AND starts_at < ? AND COALESCE(ends_at,starts_at) > ? LIMIT 1`).bind(ORG,trainerId,endsAt,startsAt).first();if(conflict)return NextResponse.json({error:'FORMATEUR_OCCUPE',message:'Ce formateur est déjà assigné pendant cette plage horaire.',conflict},{status:409})}await db.prepare(`INSERT INTO course_sessions (organization_id,cohort_id,training_id,trainer_user_id,title,delivery_mode,status,starts_at,ends_at,timezone) VALUES (?,?,?,?,?,?,'SCHEDULED',?,?,?)`).bind(ORG,cohortId,trainingId,trainerId,String(b.title||training.title).trim(),String(b.deliveryMode||'IN_PERSON'),startsAt,b.endsAt?String(b.endsAt):null,'America/Toronto').run();return NextResponse.json({ok:true},{status:201})}catch(e){return denied(e)}}
export async function DELETE(req:Request){try{const ORG=await org();const b=await req.json().catch(()=>({}));const id=Number(b.id);if(!id)return NextResponse.json({error:'Séance invalide'},{status:400});const db=getDB();const found=await db.prepare('SELECT id FROM course_sessions WHERE id=? AND organization_id=?').bind(id,ORG).first();if(!found)return NextResponse.json({error:'Séance introuvable'},{status:404});await db.prepare('DELETE FROM course_sessions WHERE id=? AND organization_id=?').bind(id,ORG).run();return NextResponse.json({ok:true})}catch(e){return denied(e)}}
