'use client';
import {useParams} from 'next/navigation';import {useEffect,useState} from 'react';
type Block={type:string;title:string;content:Record<string,any>;durationMinutes:number|null;visibility:string};
const letters=['A','B','C','D'];
export default function Projection(){const{code}=useParams<{code:string}>();const[state,setState]=useState('LOBBY');const[index,setIndex]=useState(0);const[blocks,setBlocks]=useState<Block[]>([]);const[title,setTitle]=useState('ÉVOOT!');const[count,setCount]=useState(0);const[responses,setResponses]=useState(0);const[distribution,setDistribution]=useState<number[]>([]);useEffect(()=>{const poll=()=>fetch(`/api/sessions/${code}`,{cache:'no-store'}).then(r=>r.json()).then(d=>{setState(d.session?.state||'LOBBY');setIndex(Number(d.session?.current_question||0));setBlocks((d.liveBlocks||[]).filter((b:Block)=>b.visibility!=='TRAINER'&&b.type!=='TRAINER_NOTE'));setTitle(d.training?.title||'ÉVOOT!');setCount((d.participants||[]).length);setResponses(d.responses?.count||0);setDistribution(d.responses?.distribution||[])}).catch(()=>{});poll();const id=setInterval(poll,1200);return()=>clearInterval(id)},[code]);
// Host index includes trainer-only blocks; locate visible block by original stream position count.
const visibleBefore=(blocks as any);const block=state==='BLOCK'?blocks[Math.min(index,Math.max(0,blocks.length-1))]:null;
if(state==='LOBBY')return <Screen><div className="projEyebrow">{title}</div><h1>Rejoignez la séance</h1><div className="projCode">{code}</div><p>{count} participant{count===1?'':'s'} connecté{count===1?'':'s'}</p></Screen>;
if(state==='FINISHED')return <Screen><div className="projEyebrow">ÉVOOT!</div><h1>Merci!</h1><p>La formation est terminée.</p></Screen>;
if(!block)return <Screen><h1>{title}</h1></Screen>;
const c=block.content||{};
return <Screen><div className="projEyebrow">{block.title}</div>{block.type==='LIVE_QUESTION'?<><h1>{c.prompt||block.title}</h1><div className="projAnswers">{(c.answers||[]).map((a:string,i:number)=><div key={i}><b>{letters[i]}</b><span>{a}</span></div>)}</div><p className="projStatus">{responses} / {count} réponses</p></>:block.type==='SCENARIO'?<><h1>{block.title}</h1><p className="projLead">{c.context}</p><div className="projPanel">{c.situation}</div>{c.task&&<h2>{c.task}</h2>}</>:block.type==='ACTIVITY'?<><h1>{block.title}</h1>{c.objective&&<p className="projLead">{c.objective}</p>}<div className="projPanel">{c.instructions}</div></>:block.type==='DISCUSSION'?<><h1>{c.prompt||block.title}</h1><p className="projLead">Échangeons ensemble.</p></>:block.type==='IMAGE'?<><h1>{block.title}</h1>{c.url&&<img className="projImage" src={c.url} alt={c.alt||block.title}/>}<p>{c.caption}</p></>:block.type==='VIDEO'?<><h1>{block.title}</h1><p className="projLead">{c.intro}</p>{c.instructions&&<div className="projPanel">{c.instructions}</div>}</>:block.type==='BREAK'?<><h1>{c.message||block.title}</h1><p>{c.instructions}</p></>:block.type==='SECTION'?<><h1>{block.title}</h1><p className="projLead">{c.intro}</p>{c.objective&&<div className="projPanel"><b>Objectif</b><br/>{c.objective}</div>}</>:<><h1>{block.title}</h1><p className="projLead">{c.text}</p>{c.keyPoint&&<div className="projPanel">{c.keyPoint}</div>}</>}</Screen>}
function Screen({children}:{children:React.ReactNode}){return <main style={{minHeight:'100vh',background:'#080808',color:'#fff',display:'grid',placeItems:'center',fontFamily:'Arial,sans-serif'}}><section style={{width:'min(1500px,90vw)',textAlign:'center',padding:'5vh 2vw'}}>{children}<style>{`.projEyebrow{color:#F7941D;font-weight:900;letter-spacing:.14em;text-transform:uppercase;font-size:clamp(16px,2vw,28px);margin-bottom:3vh}h1{font-size:clamp(48px,7vw,110px);line-height:1.02;margin:0 auto 4vh;max-width:1400px}h2{font-size:clamp(30px,4vw,64px);margin-top:4vh}.projCode{font-size:clamp(90px,15vw,230px);font-weight:1000;letter-spacing:.08em;color:#F7941D}.projLead,p{font-size:clamp(24px,3vw,48px);line-height:1.35}.projPanel{background:#171717;border:2px solid #333;border-left:8px solid #F7941D;border-radius:20px;padding:3vh 3vw;font-size:clamp(26px,3vw,50px);line-height:1.35;text-align:left;margin:4vh auto;max-width:1200px}.projAnswers{display:grid;grid-template-columns:1fr 1fr;gap:2vh 2vw;max-width:1300px;margin:auto}.projAnswers div{display:flex;align-items:center;text-align:left;background:#171717;border:2px solid #333;border-radius:18px;padding:2vh 2vw;font-size:clamp(22px,2.4vw,40px)}.projAnswers b{display:grid;place-items:center;min-width:60px;height:60px;border-radius:12px;background:#F7941D;color:#111;margin-right:20px}.projStatus{color:#aaa}.projImage{max-width:90%;max-height:62vh;object-fit:contain;border-radius:18px}@media(max-width:800px){.projAnswers{grid-template-columns:1fr}}`}</style></section></main>}
