'use client';
import {useEffect,useRef,useState} from 'react';
type Member={id:string;role:string;sessionId:string;tracks:Array<{trackName:string;kind:string}>};
const roomId='evoofi-first-room';
export default function RealtimeTest(){const local=useRef<HTMLVideoElement>(null),remote=useRef<HTMLVideoElement>(null),pc=useRef<RTCPeerConnection|null>(null),stream=useRef<MediaStream|null>(null);const[id]=useState(()=>crypto.randomUUID()),[status,setStatus]=useState('Prêt'),[detail,setDetail]=useState(''),[members,setMembers]=useState<Member[]>([]),[role,setRole]=useState<'trainer'|'learner'>('learner');
async function join(){try{setDetail('');setStatus('1/5 · Ouverture caméra/micro…');const ms=await navigator.mediaDevices.getUserMedia({video:true,audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});stream.current=ms;if(local.current)local.current.srcObject=ms;setStatus('2/5 · Création session Cloudflare…');const sr=await fetch('/api/realtime/session',{method:'POST'});const st=await sr.text();let sj:any={};try{sj=JSON.parse(st)}catch{}if(!sr.ok||!sj.sessionId)throw Error(`SESSION ${sr.status} · ${sj.error||st||'sessionId absent'}`);const p=new RTCPeerConnection({iceServers:[{urls:'stun:stun.cloudflare.com:3478'}]});pc.current=p;const wanted:any[]=[];for(const t of ms.getTracks()){const tr=p.addTransceiver(t,{direction:'sendonly'});wanted.push({location:'local',mid:tr.mid||String(wanted.length),trackName:`${id}-${t.kind}`})}setStatus('3/5 · Création offre WebRTC…');const offer=await p.createOffer();await p.setLocalDescription(offer);setStatus('4/5 · Publication audio/vidéo…');const rr=await fetch('/api/realtime/tracks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId:sj.sessionId,sdp:offer.sdp,tracks:wanted})});const rt=await rr.text();let rj:any={};try{rj=JSON.parse(rt)}catch{}if(!rr.ok)throw Error(`TRACKS ${rr.status} · ${rj.error||rt||'réponse vide'}`);const ans=rj.sessionDescription||rj.session_description;if(!ans?.sdp)throw Error(`TRACKS ${rr.status} · réponse SDP absente`);setStatus('5/5 · Finalisation WebRTC…');await p.setRemoteDescription({type:'answer',sdp:ans.sdp});p.oniceconnectionstatechange=()=>setDetail(`ICE: ${p.iceConnectionState} · WebRTC: ${p.connectionState}`);const roomResponse=await fetch('/api/realtime/room',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({roomId,id,role,sessionId:sj.sessionId,tracks:ms.getTracks().map(t=>({trackName:`${id}-${t.kind}`,kind:t.kind}))})});if(!roomResponse.ok)throw Error(`ROOM ${roomResponse.status} · présence EVOO-FI impossible`);setStatus('● Connecté à EVOO-FI Realtime');setDetail(`Session Cloudflare créée · ${ms.getTracks().length} pistes publiées`);await refresh()}catch(e:any){console.error(e);setStatus('Connexion impossible');setDetail(e?.message||String(e)||'Erreur inconnue')}}
async function refresh(){try{const r=await fetch(`/api/realtime/room?roomId=${roomId}`,{cache:'no-store'});if(!r.ok)return;const j=await r.json();setMembers(j.members||[])}catch{}}
useEffect(()=>{const t=setInterval(refresh,2500);return()=>{clearInterval(t);stream.current?.getTracks().forEach(x=>x.stop());pc.current?.close();fetch(`/api/realtime/room?roomId=${roomId}&id=${id}`,{method:'DELETE',keepalive:true})}},[id]);
return <main style={{minHeight:'100vh',background:'#080808',color:'white',padding:24,fontFamily:'Arial'}}><h1>EVOO-FI <span style={{color:'#F7941D'}}>REALTIME LAB</span></h1><p>Premier test PC ↔ téléphone.</p><div style={{display:'flex',gap:12,margin:'20px 0',flexWrap:'wrap'}}><button onClick={()=>setRole('trainer')}>Je suis formateur</button><button onClick={()=>setRole('learner')}>Je suis participant</button><button onClick={join} style={{background:'#F7941D',padding:'12px 18px',border:0,fontWeight:800}}>Entrer dans la salle</button></div><p>{status} · rôle: {role}</p>{detail&&<pre style={{whiteSpace:'pre-wrap',background:'#181818',border:'1px solid #333',padding:12,borderRadius:10,color:'#ffb45b'}}>{detail}</pre>}<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:18}}><section><h3>Moi</h3><video ref={local} autoPlay muted playsInline style={{width:'100%',background:'#111',borderRadius:16}}/></section><section><h3>Autres appareils détectés ({members.filter(x=>x.id!==id).length})</h3><video ref={remote} autoPlay playsInline style={{width:'100%',background:'#111',borderRadius:16}}/><div>{members.filter(x=>x.id!==id).map(x=><p key={x.id}>● {x.role} · {x.tracks.length} piste(s)</p>)}</div></section></div><p style={{opacity:.6,marginTop:30}}>Diagnostic actif : si la connexion échoue, copie-moi exactement le message orange affiché au-dessus.</p></main>}
