'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useEffect, useState } from 'react';

const answers=['Lancer mon café au client','Aller pleurer dans le backstore','Lui expliquer immédiatement pourquoi il a tort','Prendre une pause et écouter activement'];
const letters=['A','B','C','D'];
type Participant={id:number;name:string;job_title:string|null};
export default function LiveLobbyPage(){
 const params=useParams<{code:string}>();const code=String(params.code||'');const [state,setState]=useState('LOBBY');const [participants,setParticipants]=useState<Participant[]>([]);const [error,setError]=useState('');const [responseCount,setResponseCount]=useState(0);const [distribution,setDistribution]=useState<number[]>([0,0,0,0]);const [showResults,setShowResults]=useState(false);
 useEffect(()=>{if(!code)return;const poll=async()=>{try{const r=await fetch(`/api/sessions/${code}`,{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error);setState(d.session.state);setParticipants(d.participants||[]);setResponseCount(d.responses?.count||0);setDistribution(d.responses?.distribution||[0,0,0,0]);setError('');}catch(err){setError(err instanceof Error?err.message:'Erreur de connexion.');}};poll();const id=setInterval(poll,1500);return()=>clearInterval(id);},[code]);
 async function start(){const r=await fetch(`/api/sessions/${code}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({state:'QUESTION',currentQuestion:0})});if(r.ok){setState('QUESTION');setShowResults(false);}}
 const participantCount=participants.length;const progress=participantCount?Math.min(100,(responseCount/participantCount)*100):0;
 return <main className="liveHostPage"><header className="liveHostTop"><Link className="brand" href="/dashboard">ÉV<span>OO</span>T!</Link><span className="liveBadge">● LIVE</span></header><section className="liveHostHero"><div className="eyebrow">COMPRENDRE SES RÉACTIONS</div>{error&&<p>{error}</p>}{state==='LOBBY'?<><h1>Code de séance</h1><div className="sessionCode">{code}</div><p>Les participants vont sur ÉVOOT, entrent ce code, leur nom et leur poste.</p><div className="joinAddress">evoot.dadou195.workers.dev/join?code={code}</div><section className="participantLobby"><div><small>PARTICIPANTS</small><strong>{participantCount}</strong></div><div className="participantNames">{participantCount?participants.map(p=><span key={p.id}>{p.name}{p.job_title?` · ${p.job_title}`:''}</span>):<p>En attente des participants…</p>}</div></section><button className="primary liveLaunch" disabled={!participantCount} onClick={start}>Commencer la formation →</button></>:<section className="liveQuestionStage"><div className="liveQuestionMeta"><span>QUESTION 1</span><b>TON RÉFLEXE</b></div><h1>Un client arrive très fâché. Ton premier réflexe?</h1><div className="responseStatus"><div className="responseStatusText"><strong>{responseCount} / {participantCount}</strong><span>ont répondu</span></div><div className="responseTrack"><div style={{width:`${progress}%`}} /></div></div><div className={`answerGrid ${showResults?'resultsVisible':''}`}>{answers.map((answer,i)=>{const count=distribution[i]||0;const percent=responseCount?Math.round((count/responseCount)*100):0;return <article className="answerCard" key={answer}><div className="answerTop"><span className="answerLetter">{letters[i]}</span><p>{answer}</p>{showResults&&<strong className="answerPercent">{percent}%</strong>}</div>{showResults&&<><div className="answerResultTrack">{percent>0&&<div style={{width:`${percent}%`}} />}</div><small>{count} réponse{count===1?'':'s'}</small></>}</article>})}</div><div className="hostControls"><button className="secondary" onClick={()=>setShowResults(v=>!v)}>{showResults?'Masquer les résultats':'Afficher les résultats'}</button><button className="primary">Passer à la discussion →</button></div></section>}</section></main>;
}
