'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useEffect, useState } from 'react';

type Question={stage:string;prompt:string;answers:string[];why:string;relances:string[]};
type Participant={id:number;name:string;job_title:string|null};
const letters=['A','B','C','D','E','F'];
export default function LiveLobbyPage(){
 const params=useParams<{code:string}>();const code=String(params.code||'');const [state,setState]=useState('LOBBY');const [questionIndex,setQuestionIndex]=useState(0);const [participants,setParticipants]=useState<Participant[]>([]);const [questions,setQuestions]=useState<Question[]>([]);const [trainingTitle,setTrainingTitle]=useState('Formation');const [error,setError]=useState('');const [responseCount,setResponseCount]=useState(0);const [distribution,setDistribution]=useState<number[]>([]);const [showResults,setShowResults]=useState(false);const [aiSuggestion,setAiSuggestion]=useState('');const [aiLoading,setAiLoading]=useState(false);const [aiError,setAiError]=useState('');
 useEffect(()=>{if(!code)return;const poll=async()=>{try{const r=await fetch(`/api/sessions/${code}`,{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error);setState(d.session.state);setQuestionIndex(Number(d.session.current_question||0));setParticipants(d.participants||[]);setQuestions(d.questions||[]);setTrainingTitle(d.training?.title||'Formation');setResponseCount(d.responses?.count||0);setDistribution(d.responses?.distribution||[]);setError('');}catch(err){setError(err instanceof Error?err.message:'Erreur de connexion.');}};poll();const id=setInterval(poll,1500);return()=>clearInterval(id);},[code]);
 async function updateSession(nextState:string,nextQuestion=questionIndex){const r=await fetch(`/api/sessions/${code}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({state:nextState,currentQuestion:nextQuestion})});if(r.ok){setState(nextState);setQuestionIndex(nextQuestion);setShowResults(false);setAiSuggestion('');setAiError('');}}
 const q=questions[Math.min(questionIndex,Math.max(0,questions.length-1))];
 async function askAi(){if(!q)return;setAiLoading(true);setAiError('');try{const r=await fetch('/api/ai/facilitator',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q.prompt,answers:q.answers,distribution,objective:q.why})});const d=await r.json();if(!r.ok)throw new Error(d.error);setAiSuggestion(d.suggestion);}catch(err){setAiError(err instanceof Error?err.message:'Assistant ÉVOOT indisponible.');}finally{setAiLoading(false);}}
 const participantCount=participants.length;const progress=participantCount?Math.min(100,(responseCount/participantCount)*100):0;
 if(!q&&state!=='LOBBY'&&state!=='FINISHED')return <main className="liveHostPage"><section className="liveHostHero"><h1>Chargement de la formation…</h1>{error&&<p>{error}</p>}</section></main>;
 if(state==='DISCUSSION'&&q)return <main className="liveHostPage"><header className="liveHostTop"><Link className="brand" href="/dashboard">ÉV<span>OO</span>T!</Link><span className="liveBadge">● DISCUSSION</span></header><section className="discussionStage"><div className="liveQuestionMeta"><span>QUESTION {questionIndex+1} / {questions.length}</span><b>{q.stage}</b></div><h1>On en parle.</h1><section className="discussionWhy"><small>POURQUOI CETTE QUESTION?</small><p>{q.why}</p></section><section className="discussionPrompts"><small>RELANCES AU GROUPE</small>{q.relances.map((r,i)=><article key={r}><span>{i+1}</span><p>{r}</p></article>)}</section><section className="discussionWhy" style={{marginTop:18}}><small>✦ ASSISTANT ÉVOOT · PRIVÉ FORMATEUR</small>{!aiSuggestion&&!aiLoading&&<p>Analyse les réponses réelles du groupe et propose des pistes de discussion adaptées.</p>}{aiLoading&&<p>ÉVOOT analyse le groupe…</p>}{aiSuggestion&&<p style={{whiteSpace:'pre-wrap'}}>{aiSuggestion}</p>}{aiError&&<p>{aiError}</p>}<button className="secondary" style={{marginTop:14}} disabled={aiLoading||responseCount===0} onClick={askAi}>{aiLoading?'Analyse…':aiSuggestion?'Réanalyser les réponses':'✦ Analyser avec l’IA'}</button></section><div className="hostControls">{questionIndex+1<questions.length?<button className="primary" onClick={()=>updateSession('QUESTION',questionIndex+1)}>Continuer → Question {questionIndex+2}</button>:<button className="primary" onClick={()=>updateSession('FINISHED',questionIndex)}>Terminer la séance →</button>}</div></section></main>;
 return <main className="liveHostPage"><header className="liveHostTop"><Link className="brand" href="/dashboard">ÉV<span>OO</span>T!</Link><span className="liveBadge">● LIVE</span></header><section className="liveHostHero"><div className="eyebrow">{trainingTitle.toUpperCase()}</div>{error&&<p>{error}</p>}{state==='LOBBY'?<><h1>Code de séance</h1><div className="sessionCode">{code}</div><p>Les participants vont sur ÉVOOT, entrent ce code, leur nom et leur poste.</p><div className="joinAddress">evoot.dadou195.workers.dev/join?code={code}</div><section className="participantLobby"><div><small>PARTICIPANTS</small><strong>{participantCount}</strong></div><div className="participantNames">{participantCount?participants.map(p=><span key={p.id}>{p.name}{p.job_title?` · ${p.job_title}`:''}</span>):<p>En attente des participants…</p>}</div></section><button className="primary liveLaunch" disabled={!participantCount||!questions.length} onClick={()=>updateSession('QUESTION',0)}>Commencer la formation →</button></>:state==='FINISHED'?<section className="discussionStage"><div className="eyebrow">SÉANCE TERMINÉE</div><h1>Merci au groupe.</h1><p>Vous venez de passer du réflexe automatique à une réponse plus consciente et plus efficace.</p></section>:q&&<section className="liveQuestionStage"><div className="liveQuestionMeta"><span>QUESTION {questionIndex+1} / {questions.length}</span><b>{q.stage}</b></div><h1>{q.prompt}</h1><div className="responseStatus"><div className="responseStatusText"><strong>{responseCount} / {participantCount}</strong><span>ont répondu</span></div><div className="responseTrack"><div style={{width:`${progress}%`}} /></div></div><div className={`answerGrid ${showResults?'resultsVisible':''}`}>{q.answers.map((answer,i)=>{const count=distribution[i]||0;const percent=responseCount?Math.round((count/responseCount)*100):0;return <article className="answerCard" key={answer}><div className="answerTop"><span className="answerLetter">{letters[i]||String(i+1)}</span><p>{answer}</p>{showResults&&<strong className="answerPercent">{percent}%</strong>}</div>{showResults&&<><div className="answerResultTrack">{percent>0&&<div style={{width:`${percent}%`}} />}</div><small>{count} réponse{count===1?'':'s'}</small></>}</article>})}</div><div className="hostControls"><button className="secondary" onClick={()=>setShowResults(v=>!v)}>{showResults?'Masquer les résultats':'Afficher les résultats'}</button><button className="primary" onClick={()=>updateSession('DISCUSSION')}>Passer à la discussion →</button></div></section>}</section></main>;
}
