'use client';
import Link from 'next/link';
import {useParams} from 'next/navigation';
import {useEffect,useState} from 'react';
type Participant={id:number;name:string;job_title:string|null};
type Block={position:number;type:string;title:string;content:Record<string,any>;durationMinutes:number|null;visibility:string};
const letters=['A','B','C','D','E','F'];
const labels:Record<string,string>={SECTION:'SECTION',TEXT:'CONTENU',IMAGE:'IMAGE',VIDEO:'VIDÉO',ACTIVITY:'ACTIVITÉ',SCENARIO:'SCÉNARIO',LIVE_QUESTION:'QUESTION LIVE',DISCUSSION:'DISCUSSION',TRAINER_NOTE:'NOTE FORMATEUR',BREAK:'PAUSE'};
export default function LiveLobbyPage(){
 const params=useParams<{code:string}>();const code=String(params.code||'');const[state,setState]=useState('LOBBY');const[index,setIndex]=useState(0);const[participants,setParticipants]=useState<Participant[]>([]);const[blocks,setBlocks]=useState<Block[]>([]);const[trainingTitle,setTrainingTitle]=useState('Formation');const[error,setError]=useState('');const[responseCount,setResponseCount]=useState(0);const[distribution,setDistribution]=useState<number[]>([]);const[showResults,setShowResults]=useState(false);const[aiSuggestion,setAiSuggestion]=useState('');const[aiLoading,setAiLoading]=useState(false);const[currentQuestionIndex,setCurrentQuestionIndex]=useState(-1);
 useEffect(()=>{if(!code)return;const poll=async()=>{try{const r=await fetch(`/api/sessions/${code}`,{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error);setState(d.session.state);setIndex(Number(d.session.current_question||0));setParticipants(d.participants||[]);setBlocks(d.liveBlocks||[]);setTrainingTitle(d.training?.title||'Formation');setResponseCount(d.responses?.count||0);setDistribution(d.responses?.distribution||[]);setCurrentQuestionIndex(Number(d.currentQuestionIndex??-1));setError('')}catch(e){setError(e instanceof Error?e.message:'Erreur de connexion.')}};poll();const id=setInterval(poll,1500);return()=>clearInterval(id)},[code]);
 async function update(nextState:string,nextIndex=index){const r=await fetch(`/api/sessions/${code}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({state:nextState,currentQuestion:nextIndex})});if(r.ok){setState(nextState);setIndex(nextIndex);setShowResults(false);setAiSuggestion('')}}
 const block=blocks[index];const count=participants.length;const progress=count?Math.min(100,responseCount/count*100):0;const last=index>=blocks.length-1;
 async function next(){if(last)return update('FINISHED',index);return update('BLOCK',index+1)}
 async function askAi(){if(!block||block.type!=='LIVE_QUESTION')return;setAiLoading(true);try{const r=await fetch('/api/ai/facilitator',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:block.content.prompt,answers:block.content.answers||[],distribution,objective:block.content.why||''})});const d=await r.json();if(r.ok)setAiSuggestion(d.suggestion||'')}finally{setAiLoading(false)}}
 if(state==='LOBBY')return <main className="liveHostPage"><header className="liveHostTop"><Link className="brand" href="/dashboard">ÉV<span>OO</span>T!</Link><span className="liveBadge">● LIVE</span></header><section className="liveHostHero"><div className="eyebrow">{trainingTitle.toUpperCase()}</div><h1>Code de séance</h1><div className="sessionCode">{code}</div><p>Les participants entrent ce code sur ÉVOOT.</p><section className="participantLobby"><div><small>PARTICIPANTS</small><strong>{count}</strong></div><div className="participantNames">{count?participants.map(p=><span key={p.id}>{p.name}{p.job_title?` · ${p.job_title}`:''}</span>):<p>En attente des participants…</p>}</div></section><button className="primary liveLaunch" disabled={!count||!blocks.length} onClick={()=>update('BLOCK',0)}>Commencer la formation →</button>{error&&<p>{error}</p>}</section></main>;
 if(state==='FINISHED')return <main className="liveHostPage"><header className="liveHostTop"><Link className="brand" href="/dashboard">ÉV<span>OO</span>T!</Link><span className="liveBadge">TERMINÉ</span></header><section className="discussionStage"><div className="eyebrow">SÉANCE TERMINÉE</div><h1>Formation terminée.</h1><p>Le scénario complet a été parcouru.</p></section></main>;
 if(!block)return <main className="liveHostPage"><section className="liveHostHero"><h1>Chargement du scénario…</h1></section></main>;
 const text=String(block.content.text||'');const answers=(block.content.answers||[]) as string[];const relances=(block.content.relances||[]) as string[];
 return <main className="liveHostPage"><header className="liveHostTop"><Link className="brand" href="/dashboard">ÉV<span>OO</span>T!</Link><span className="liveBadge">● {labels[block.type]||block.type}</span></header><section className="scenarioPlayer"><div className="liveQuestionMeta"><span>BLOC {index+1} / {blocks.length}</span><b>{labels[block.type]||block.type}</b>{block.durationMinutes&&<span>· {block.durationMinutes} MIN</span>}</div>
 {block.type==='TRAINER_NOTE'?<section className="trainerPrivateStage"><div className="eyebrow">PRIVÉ · FORMATEUR SEULEMENT</div><h1>{block.title}</h1><p>{text}</p></section>:block.type==='LIVE_QUESTION'?<><h1>{block.content.prompt||block.title}</h1><div className="responseStatus"><div className="responseStatusText"><strong>{responseCount} / {count}</strong><span>ont répondu</span></div><div className="responseTrack"><div style={{width:`${progress}%`}}/></div></div><div className={`answerGrid ${showResults?'resultsVisible':''}`}>{answers.map((a,i)=>{const c=distribution[i]||0;const pct=responseCount?Math.round(c/responseCount*100):0;return <article className="answerCard" key={i}><div className="answerTop"><span className="answerLetter">{letters[i]}</span><p>{a}</p>{showResults&&<strong className="answerPercent">{pct}%</strong>}</div>{showResults&&<small>{c} réponse{c===1?'':'s'}</small>}</article>})}</div>{showResults&&<section className="discussionWhy"><small>POURQUOI CETTE QUESTION?</small><p>{block.content.why}</p></section>}{showResults&&relances.length>0&&<section className="discussionPrompts"><small>RELANCES AU GROUPE</small>{relances.map((r,i)=><article key={i}><span>{i+1}</span><p>{r}</p></article>)}</section>}{showResults&&<section className="discussionWhy"><small>✦ ASSISTANT ÉVOOT · PRIVÉ FORMATEUR</small><p style={{whiteSpace:'pre-wrap'}}>{aiSuggestion||'Analyse les réponses du groupe pour préparer la discussion.'}</p><button className="secondary" disabled={aiLoading||responseCount===0} onClick={askAi}>{aiLoading?'Analyse…':'✦ Analyser avec l’IA'}</button></section>}</>:<section className={`contentStage type-${block.type.toLowerCase()}`}><div className="eyebrow">{labels[block.type]||block.type}</div><h1>{block.title}</h1>{text&&<p>{text}</p>}{block.type==='IMAGE'&&block.content.url&&<img src={block.content.url} alt={block.title}/>} {block.type==='VIDEO'&&block.content.url&&<a className="primary" href={block.content.url} target="_blank" rel="noreferrer">▶ Ouvrir la vidéo</a>}</section>}
 <div className="hostControls">{block.type==='LIVE_QUESTION'&&<button className="secondary" onClick={()=>setShowResults(v=>!v)}>{showResults?'Masquer les résultats':'Afficher les résultats'}</button>}<button className="primary" onClick={next}>{last?'Terminer la formation →':'Bloc suivant →'}</button></div></section></main>;
}
