'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';

type Question={stage:string;prompt:string;answers:string[];why:string;relances:string[]};
const emptyQuestion=():Question=>({stage:'QUESTION',prompt:'Nouvelle question',answers:['Réponse A','Réponse B','Réponse C','Réponse D'],why:'',relances:['','','']});
export default function TrainingEditor(){
 const [title,setTitle]=useState('');const [description,setDescription]=useState('');const [questions,setQuestions]=useState<Question[]>([]);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [message,setMessage]=useState('');
 useEffect(()=>{fetch('/api/trainings/comprendre-ses-reactions',{cache:'no-store'}).then(r=>r.json()).then(d=>{if(d.training){setTitle(d.training.title);setDescription(d.training.description);setQuestions(d.training.questions||[])}else setMessage(d.error||'Erreur de chargement.')}).catch(()=>setMessage('Erreur de chargement.')).finally(()=>setLoading(false));},[]);
 const patch=(i:number,p:Partial<Question>)=>setQuestions(v=>v.map((q,j)=>j===i?{...q,...p}:q));
 const answer=(i:number,j:number,value:string)=>patch(i,{answers:questions[i].answers.map((a,k)=>k===j?value:a)});
 const relance=(i:number,j:number,value:string)=>patch(i,{relances:questions[i].relances.map((r,k)=>k===j?value:r)});
 const duplicate=(i:number)=>setQuestions(v=>[...v.slice(0,i+1),{...v[i],answers:[...v[i].answers],relances:[...v[i].relances]},...v.slice(i+1)]);
 const remove=(i:number)=>{if(questions.length>1)setQuestions(v=>v.filter((_,j)=>j!==i));};
 async function save(){setSaving(true);setMessage('');try{const r=await fetch('/api/trainings/comprendre-ses-reactions',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,description,questions})});const d=await r.json();if(!r.ok)throw new Error(d.error);setMessage('✓ Enregistré dans D1 — les prochaines séances utiliseront ces changements.');}catch(e){setMessage(e instanceof Error?e.message:'Impossible d’enregistrer.');}finally{setSaving(false)}}
 if(loading)return <main className="editorShell"><h1>Chargement de la formation…</h1></main>;
 return <main className="editorShell"><header className="editorTop"><div><Link className="brand" href="/">ÉV<span>OO</span>T!</Link><span className="crumb"> / Évolution PME</span></div><div style={{display:'flex',gap:10}}><Link className="secondary" href="/dashboard/trainings">← Formations</Link><button className="primary" onClick={save} disabled={saving}>{saving?'Enregistrement…':'Enregistrer dans D1'}</button></div></header><section className="editorHero"><div className="eyebrow">BLOC 01 · ÉDITEUR PÉDAGOGIQUE</div><input value={title} onChange={e=>setTitle(e.target.value)} style={{fontSize:'2.2rem',fontWeight:800,width:'100%',background:'transparent',color:'inherit',border:'0',borderBottom:'1px solid #333',padding:'8px 0'}}/><textarea value={description} onChange={e=>setDescription(e.target.value)} style={{width:'100%',minHeight:70,marginTop:12}}/><div className="editorMeta"><span>{questions.length} questions</span><span>Live</span><span>D1</span></div>{message&&<p>{message}</p>}</section><section className="questionList">{questions.map((q,i)=><article className="questionEditor" key={i}><div className="questionSide"><strong>Q{String(i+1).padStart(2,'0')}</strong><span>Live</span></div><div className="questionBody"><input className="stageLabel" value={q.stage} onChange={e=>patch(i,{stage:e.target.value})}/><textarea value={q.prompt} onChange={e=>patch(i,{prompt:e.target.value})} style={{width:'100%',fontSize:'1.35rem',fontWeight:700,minHeight:80,margin:'12px 0'}}/><div className="answerEditor">{q.answers.map((a,j)=><div key={j}><b>{String.fromCharCode(65+j)}</b><input value={a} onChange={e=>answer(i,j,e.target.value)} style={{width:'100%'}}/></div>)}</div><div className="trainerBox"><small>RELANCES FORMATEUR</small>{q.relances.map((r,j)=><p key={j}>→ <input value={r} onChange={e=>relance(i,j,e.target.value)} style={{width:'90%'}}/></p>)}</div><div className="synthesisBox"><small>POURQUOI CETTE QUESTION?</small><textarea value={q.why} onChange={e=>patch(i,{why:e.target.value})} style={{width:'100%',minHeight:80}}/></div><div className="questionButtons"><button className="secondary" onClick={()=>duplicate(i)}>Dupliquer</button><button className="ghost" onClick={()=>remove(i)} disabled={questions.length===1}>Supprimer</button></div></div></article>)}<button className="addQuestion" onClick={()=>setQuestions(v=>[...v,emptyQuestion()])}>+ Ajouter une question</button></section><aside className="dbtNotice">Compétences comportementales adaptées au contexte professionnel. Les concepts TCD/DBT sont crédités à Marsha M. Linehan et ne constituent pas une psychothérapie.</aside></main>;
}
