'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';

type Question={stage:string;prompt:string;answers:string[];why:string;relances:string[]};
type BlockType='SECTION'|'TEXT'|'IMAGE'|'VIDEO'|'ACTIVITY'|'SCENARIO'|'LIVE_QUESTION'|'DISCUSSION'|'TRAINER_NOTE'|'BREAK';
type Block={type:BlockType;title:string;content:Record<string,any>;durationMinutes:number|null;visibility:'LIVE'|'SELF_PACED'|'BOTH'|'TRAINER'};
const labels:Record<BlockType,string>={SECTION:'Section',TEXT:'Texte / contenu',IMAGE:'Image',VIDEO:'Vidéo',ACTIVITY:'Activité / exercice',SCENARIO:'Scénario',LIVE_QUESTION:'Question ÉVOOT Live',DISCUSSION:'Discussion',TRAINER_NOTE:'Notes formateur',BREAK:'Pause'};
const icons:Record<BlockType,string>={SECTION:'§',TEXT:'T',IMAGE:'▧',VIDEO:'▶',ACTIVITY:'✦',SCENARIO:'◇',LIVE_QUESTION:'?',DISCUSSION:'☵',TRAINER_NOTE:'✎',BREAK:'Ⅱ'};
const makeBlock=(type:BlockType):Block=>({type,title:labels[type],content:type==='LIVE_QUESTION'?{prompt:'Nouvelle question',answers:['Réponse A','Réponse B','Réponse C','Réponse D'],why:'',relances:['','','']}:{text:'',url:''},durationMinutes:null,visibility:type==='TRAINER_NOTE'?'TRAINER':'BOTH'});
const questionBlock=(q:Question):Block=>({type:'LIVE_QUESTION',title:q.stage||'Question ÉVOOT',content:{prompt:q.prompt,answers:q.answers,why:q.why,relances:q.relances},durationMinutes:null,visibility:'LIVE'});

export default function TrainingEditor(){
 const [title,setTitle]=useState('');const [description,setDescription]=useState('');const [questions,setQuestions]=useState<Question[]>([]);const [blocks,setBlocks]=useState<Block[]>([]);const [target,setTarget]=useState<number|null>(null);const [delivery,setDelivery]=useState('BOTH');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [message,setMessage]=useState('');
 useEffect(()=>{fetch('/api/trainings/comprendre-ses-reactions',{cache:'no-store'}).then(r=>r.json()).then(d=>{if(!d.training){setMessage(d.error||'Erreur de chargement.');return}const t=d.training;setTitle(t.title);setDescription(t.description);setQuestions(t.questions||[]);setTarget(t.targetDurationMinutes);setDelivery(t.deliveryMode||'BOTH');setBlocks((t.blocks?.length?t.blocks:(t.questions||[]).map(questionBlock)) as Block[])}).catch(()=>setMessage('Erreur de chargement.')).finally(()=>setLoading(false));},[]);
 const patch=(i:number,p:Partial<Block>)=>setBlocks(v=>v.map((b,j)=>j===i?{...b,...p}:b));
 const content=(i:number,p:Record<string,any>)=>patch(i,{content:{...blocks[i].content,...p}});
 const add=(type:BlockType)=>setBlocks(v=>[...v,makeBlock(type)]);
 const move=(i:number,d:number)=>setBlocks(v=>{const n=i+d;if(n<0||n>=v.length)return v;const a=[...v];[a[i],a[n]]=[a[n],a[i]];return a});
 const duplicate=(i:number)=>setBlocks(v=>{const copy=JSON.parse(JSON.stringify(v[i]));return [...v.slice(0,i+1),copy,...v.slice(i+1)]});
 const remove=(i:number)=>setBlocks(v=>v.filter((_,j)=>j!==i));
 const liveQuestions=()=>blocks.filter(b=>b.type==='LIVE_QUESTION').map(b=>({stage:b.title||'QUESTION',prompt:String(b.content.prompt||''),answers:(b.content.answers||[]).map(String),why:String(b.content.why||''),relances:(b.content.relances||[]).map(String)}));
 const totalMinutes=blocks.reduce((s,b)=>s+(Number(b.durationMinutes)||0),0);
 async function save(){setSaving(true);setMessage('');try{const qs=liveQuestions();const r=await fetch('/api/trainings/comprendre-ses-reactions',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,description,targetDurationMinutes:target,deliveryMode:delivery,blocks,questions:qs.length?qs:questions})});const d=await r.json();if(!r.ok)throw new Error(d.error);if(qs.length)setQuestions(qs);setMessage('✓ Scénario enregistré dans D1');}catch(e){setMessage(e instanceof Error?e.message:'Impossible d’enregistrer.')}finally{setSaving(false)}}
 if(loading)return <main className="scenarioEditor"><h1>Chargement de la formation…</h1></main>;
 return <main className="scenarioEditor"><header className="scenarioTop"><div><Link className="brand" href="/">ÉV<span>OO</span>T!</Link><span className="crumb"> / Constructeur</span></div><div className="scenarioTopActions"><Link className="secondary" href="/dashboard/trainings">← Formations</Link><button className="primary" onClick={save} disabled={saving}>{saving?'Enregistrement…':'Enregistrer'}</button></div></header>
 <div className="scenarioLayout"><aside className="scenarioPalette"><small>AJOUTER UN BLOC</small>{(Object.keys(labels) as BlockType[]).map(t=><button key={t} onClick={()=>add(t)}><b>{icons[t]}</b><span>{labels[t]}</span></button>)}<div className="paletteHint">Construis le déroulement complet. Chaque bloc peut être déplacé et adapté au mode de diffusion.</div></aside>
 <section className="scenarioCanvas"><div className="scenarioHero"><div className="eyebrow">FORMATION · SCÉNARIO COMPLET</div><input className="scenarioTitle" value={title} onChange={e=>setTitle(e.target.value)}/><textarea className="scenarioDescription" placeholder="Objectifs et description de la formation…" value={description} onChange={e=>setDescription(e.target.value)}/><div className="scenarioStats"><span>{blocks.length} blocs</span><span>{totalMinutes} min planifiées</span>{target?<span>{target} min cible</span>:<span>Durée libre</span>}<span>{delivery==='LIVE'?'Live':delivery==='SELF_PACED'?'Autonome':'Live + autonome'}</span></div>{message&&<div className="saveMessage">{message}</div>}</div>
 <div className="scenarioTimeline">{blocks.length===0&&<div className="emptyScenario"><strong>Ton scénario est vide.</strong><span>Ajoute un premier bloc à gauche.</span></div>}{blocks.map((b,i)=><article className={`scenarioBlock type-${b.type.toLowerCase()}`} key={i}><div className="blockRail"><span>{String(i+1).padStart(2,'0')}</span><button onClick={()=>move(i,-1)} disabled={i===0}>↑</button><button onClick={()=>move(i,1)} disabled={i===blocks.length-1}>↓</button></div><div className="blockMain"><div className="blockHead"><div className="blockKind"><b>{icons[b.type]}</b><span>{labels[b.type]}</span></div><div className="blockControls"><label><input type="number" min="0" placeholder="min" value={b.durationMinutes??''} onChange={e=>patch(i,{durationMinutes:e.target.value===''?null:Number(e.target.value)})}/> min</label><select value={b.visibility} onChange={e=>patch(i,{visibility:e.target.value as Block['visibility']})}><option value="BOTH">Live + autonome</option><option value="LIVE">Live</option><option value="SELF_PACED">Autonome</option><option value="TRAINER">Privé formateur</option></select></div></div><input className="blockTitleInput" value={b.title} onChange={e=>patch(i,{title:e.target.value})}/>
 {b.type==='SECTION'&&<textarea className="darkField" placeholder="Introduction ou objectif de cette section…" value={b.content.text||''} onChange={e=>content(i,{text:e.target.value})}/>} 
 {['TEXT','ACTIVITY','SCENARIO','DISCUSSION','TRAINER_NOTE','BREAK'].includes(b.type)&&<textarea className="darkField" placeholder={b.type==='TRAINER_NOTE'?'Écris ici le guide privé du formateur…':b.type==='ACTIVITY'?'Consignes de l’activité…':b.type==='SCENARIO'?'Décris la situation ou le scénario…':b.type==='DISCUSSION'?'Questions, pistes et relances pour la discussion…':b.type==='BREAK'?'Notes facultatives pour la pause…':'Contenu pédagogique…'} value={b.content.text||''} onChange={e=>content(i,{text:e.target.value})}/>} 
 {b.type==='IMAGE'&&<div className="mediaEditor"><div className="mediaPlaceholder">▧<strong>Image</strong><span>Le téléversement R2 sera branché à cette zone.</span></div><input className="darkInput" placeholder="URL de l’image (fonctionnel maintenant)" value={b.content.url||''} onChange={e=>content(i,{url:e.target.value})}/><textarea className="darkField compact" placeholder="Légende ou consignes…" value={b.content.text||''} onChange={e=>content(i,{text:e.target.value})}/></div>}
 {b.type==='VIDEO'&&<div className="mediaEditor"><div className="mediaPlaceholder">▶<strong>Vidéo</strong><span>Lien vidéo maintenant; stockage/Stream pourra être ajouté ensuite.</span></div><input className="darkInput" placeholder="Lien vidéo" value={b.content.url||''} onChange={e=>content(i,{url:e.target.value})}/><textarea className="darkField compact" placeholder="Notes ou consignes…" value={b.content.text||''} onChange={e=>content(i,{text:e.target.value})}/></div>}
 {b.type==='LIVE_QUESTION'&&<QuestionFields block={b} onContent={p=>content(i,p)}/>}<div className="blockActions"><button onClick={()=>duplicate(i)}>⧉ Dupliquer</button><button className="danger" onClick={()=>remove(i)}>Supprimer</button></div></div></article>)}</div>
 <div className="scenarioQuick"><span>Ajouter rapidement</span>{(['TEXT','IMAGE','VIDEO','ACTIVITY','LIVE_QUESTION','TRAINER_NOTE'] as BlockType[]).map(t=><button key={t} onClick={()=>add(t)}>{icons[t]} {labels[t]}</button>)}</div></section>
 <aside className="scenarioSettings"><small>PARAMÈTRES</small><label>Mode de diffusion<select value={delivery} onChange={e=>setDelivery(e.target.value)}><option value="BOTH">Live + autonome</option><option value="LIVE">Live avec formateur</option><option value="SELF_PACED">Formation autonome</option></select></label><label>Durée cible (minutes)<input type="number" min="0" placeholder="Libre" value={target??''} onChange={e=>setTarget(e.target.value===''?null:Number(e.target.value))}/></label><div className="timeCard"><small>DÉROULEMENT</small><strong>{totalMinutes} min</strong>{target&&<><span>sur {target} min</span><div><i style={{width:`${Math.min(100,totalMinutes/target*100)}%`}}/></div></>}</div><div className="settingsNote"><b>Un seul éditeur.</b><p>Les mêmes blocs peuvent servir en Live, en autonome ou dans les deux parcours. Les notes formateur restent privées.</p></div></aside></div></main>;
}

function QuestionFields({block,onContent}:{block:Block;onContent:(p:Record<string,any>)=>void}){const answers=(block.content.answers||['','','','']) as string[];const relances=(block.content.relances||['','','']) as string[];return <div className="liveQuestionEditor"><textarea className="questionPrompt" value={block.content.prompt||''} placeholder="Question ou situation…" onChange={e=>onContent({prompt:e.target.value})}/><div className="scenarioAnswers">{answers.map((a,j)=><label key={j}><b>{String.fromCharCode(65+j)}</b><input value={a} onChange={e=>onContent({answers:answers.map((x,k)=>k===j?e.target.value:x)})}/></label>)}</div><div className="pedagogyGrid"><div><small>POURQUOI CETTE QUESTION?</small><textarea className="darkField" value={block.content.why||''} onChange={e=>onContent({why:e.target.value})}/></div><div><small>RELANCES FORMATEUR</small>{relances.map((r,j)=><input className="darkInput" key={j} value={r} placeholder={`Relance ${j+1}`} onChange={e=>onContent({relances:relances.map((x,k)=>k===j?e.target.value:x)})}/>)}</div></div></div>}
