import Link from 'next/link';

const questions=[
{stage:'OUVERTURE · TON RÉFLEXE',type:'Choix multiple',prompt:'Un client arrive très fâché et hausse le ton. Ton premier réflexe est…',answers:['Lui lancer mon café dessus','Aller pleurer en arrière','Expliquer immédiatement mon point de vue','Écouter activement avant de répondre'],relances:['Pourquoi ce choix te vient-il spontanément?','Quelle serait la version subtile de « lancer son café » au travail?'],synthese:'Avant de choisir une stratégie, reconnaître son impulsion permet de créer un espace entre la réaction automatique et la réponse professionnelle.'},
{stage:'OUVERTURE · TON RÉFLEXE',type:'Choix multiple',prompt:'Un client te répond sèchement. Quelle interprétation apparaît le plus vite?',answers:['Il me manque de respect','Il passe probablement une mauvaise journée','J’ai sûrement fait quelque chose de travers','Je ne sais pas encore ce qui explique son ton'],relances:['Qu’est-ce qui est un fait ici?','Qu’est-ce qui est une interprétation?'],synthese:'Une interprétation peut sembler évidente sans être un fait. La distinguer aide à éviter d’escalader inutilement une interaction.'},
{stage:'INTÉGRATION · ET MAINTENANT?',type:'Scénario',prompt:'Tu sens que tu vas répondre trop vite à une remarque irritante. Quelle action est la plus utile?',answers:['Répondre immédiatement pour ne pas perdre la face','Faire une pause volontaire avant de répondre','Ignorer complètement la personne','Prouver que j’ai raison'],relances:['À quoi ressemble une pause professionnelle de cinq secondes?','Que peut changer STOP dans cette situation?'],synthese:'La compétence STOP, issue de la TCD/DBT de Marsha Linehan, permet d’interrompre une réaction impulsive afin d’observer puis d’agir plus efficacement.'},
{stage:'ÉVALUATION · METS-LE EN PRATIQUE',type:'Scénario',prompt:'Dans une interaction difficile, qu’est-ce qui indique le mieux une réponse efficace?',answers:['J’ai réussi à avoir raison','L’autre personne s’est excusée','J’ai distingué les faits, mon interprétation, mon émotion et mon impulsion avant d’agir','Je n’ai ressenti aucune émotion'],relances:['Efficace veut-il dire ne rien ressentir?','Quel élément peut-on réellement contrôler?'],synthese:'L’objectif n’est pas de supprimer les émotions, mais de mieux comprendre ce qui se passe en soi pour choisir une réponse adaptée au contexte.'}
];
export default function TrainingEditor(){return <main className="editorShell"><header className="editorTop"><div><Link className="brand" href="/">ÉV<span>OO</span>T!</Link><span className="crumb"> / Évolution PME</span></div><Link className="secondary" href="/dashboard/trainings">← Formations</Link></header><section className="editorHero"><div className="eyebrow">BLOC 01 · ÉDITEUR PÉDAGOGIQUE</div><h1>Comprendre ses réactions</h1><p>Reconnaître émotions, interprétations et impulsions afin de choisir une réponse plus efficace.</p><div className="editorMeta"><span>4 questions préparées</span><span>Live</span><span>Brouillon</span></div></section><section className="questionList">{questions.map((q,i)=><article className="questionEditor" key={q.prompt}><div className="questionSide"><strong>Q{String(i+1).padStart(2,'0')}</strong><span>{q.type}</span></div><div className="questionBody"><div className="stageLabel">{q.stage}</div><h2>{q.prompt}</h2><div className="answerEditor">{q.answers.map((a,j)=><div key={a}><b>{String.fromCharCode(65+j)}</b><span>{a}</span></div>)}</div><div className="trainerBox"><small>RELANCES FORMATEUR</small>{q.relances.map(r=><p key={r}>→ {r}</p>)}</div><div className="synthesisBox"><small>SYNTHÈSE PÉDAGOGIQUE</small><p>{q.synthese}</p></div><div className="questionButtons"><button className="secondary">Modifier</button><button className="ghost">Dupliquer</button></div></div></article>)}<button className="addQuestion">+ Ajouter une question</button></section><aside className="dbtNotice">Compétences comportementales adaptées au contexte professionnel. Les concepts TCD/DBT sont crédités à Marsha M. Linehan et ne constituent pas une psychothérapie.</aside></main>}
