'use client';
import {useEffect,useRef,useState} from 'react';
type Device={deviceId:string;label:string};
export default function MediaPreflight(){
 const videoRef=useRef<HTMLVideoElement>(null),streamRef=useRef<MediaStream|null>(null),pcRef=useRef<RTCPeerConnection|null>(null);
 const[cameras,setCameras]=useState<Device[]>([]),[mics,setMics]=useState<Device[]>([]),[camera,setCamera]=useState(''),[mic,setMic]=useState(''),[camOn,setCamOn]=useState(true),[micOn,setMicOn]=useState(true),[status,setStatus]=useState('Prêt à tester la caméra et le micro.'),[level,setLevel]=useState(0),[live,setLive]=useState(false);
 async function loadDevices(){const d=await navigator.mediaDevices.enumerateDevices();const cs=d.filter(x=>x.kind==='videoinput').map((x,i)=>({deviceId:x.deviceId,label:x.label||`Caméra ${i+1}`}));const ms=d.filter(x=>x.kind==='audioinput').map((x,i)=>({deviceId:x.deviceId,label:x.label||`Micro ${i+1}`}));setCameras(cs);setMics(ms);if(!camera&&cs[0])setCamera(cs[0].deviceId);if(!mic&&ms[0])setMic(ms[0].deviceId)}
 async function start(){try{stop();setStatus('Demande des permissions…');const stream=await navigator.mediaDevices.getUserMedia({video:camera?{deviceId:{exact:camera}}:true,audio:mic?{deviceId:{exact:mic},echoCancellation:true,noiseSuppression:true,autoGainControl:true}:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});streamRef.current=stream;if(videoRef.current)videoRef.current.srcObject=stream;stream.getVideoTracks().forEach(t=>t.enabled=camOn);stream.getAudioTracks().forEach(t=>t.enabled=micOn);await loadDevices();meter(stream);setStatus('Caméra et micro prêts.');}catch(e:any){setStatus(e?.name==='NotAllowedError'?'Permission refusée. Autorise la caméra et le micro dans le navigateur.':'Impossible d’ouvrir les appareils. Vérifie qu’ils ne sont pas utilisés ailleurs.')}}
 async function connect(){try{let stream=streamRef.current;if(!stream){await start();stream=streamRef.current}if(!stream)throw new Error('media');setStatus('Connexion à la salle EVOO-FI…');const sr=await fetch('/api/realtime/session',{method:'POST'}),sj=await sr.json();if(!sr.ok||!sj.sessionId)throw new Error(sj.error||'session');const pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.cloudflare.com:3478'}]});pcRef.current=pc;const tracks:{location:'local';mid:string;trackName:string}[]=[];for(const track of stream.getTracks()){const transceiver=pc.addTransceiver(track,{direction:'sendonly'});tracks.push({location:'local',mid:transceiver.mid||String(tracks.length),trackName:`trainer-${track.kind}-${track.id}`})}const offer=await pc.createOffer();await pc.setLocalDescription(offer);const tr=await fetch('/api/realtime/tracks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId:sj.sessionId,sdp:offer.sdp,tracks})}),tj=await tr.json();if(!tr.ok)throw new Error(tj.error||'tracks');const answer=tj.sessionDescription||tj.session_description;if(!answer?.sdp)throw new Error('answer');await pc.setRemoteDescription({type:'answer',sdp:answer.sdp});pc.onconnectionstatechange=()=>{if(pc.connectionState==='connected'){setLive(true);setStatus('Connecté à Cloudflare Realtime · caméra et micro diffusés.')}else if(['failed','disconnected','closed'].includes(pc.connectionState)){setLive(false);setStatus('Connexion Realtime interrompue.')}};setStatus('Négociation WebRTC en cours…');}catch(e){console.error(e);setLive(false);setStatus('Connexion Realtime impossible. Réessaie après le déploiement.') }}
 function stop(){pcRef.current?.close();pcRef.current=null;setLive(false);streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;if(videoRef.current)videoRef.current.srcObject=null;setLevel(0)}
 function meter(stream:MediaStream){try{const Ctx=(window.AudioContext||(window as any).webkitAudioContext);const ctx=new Ctx(),src=ctx.createMediaStreamSource(stream),an=ctx.createAnalyser();an.fftSize=256;src.connect(an);const a=new Uint8Array(an.frequencyBinCount);const tick=()=>{if(streamRef.current!==stream){ctx.close();return}an.getByteFrequencyData(a);setLevel(Math.min(100,Math.round(a.reduce((s,v)=>s+v,0)/a.length)));requestAnimationFrame(tick)};tick()}catch{}}
 useEffect(()=>()=>stop(),[]);useEffect(()=>{streamRef.current?.getVideoTracks().forEach(t=>t.enabled=camOn)},[camOn]);useEffect(()=>{streamRef.current?.getAudioTracks().forEach(t=>t.enabled=micOn)},[micOn]);
 return <div className="mediaPreflight"><div className="viewTitle"><span>EVOO-FI · AUDIO / VIDÉO</span><h2>Préparer ma caméra et mon micro.</h2></div><div className="mediaPreflightGrid"><div className="mediaPreview"><video ref={videoRef} autoPlay muted playsInline/><div className="mediaPreviewBadge">{live?'● EN DIRECT · REALTIME':'APERÇU LOCAL · non diffusé'}</div></div><div className="mediaSetup"><label>Caméra<select value={camera} onChange={e=>setCamera(e.target.value)}>{cameras.map(x=><option key={x.deviceId} value={x.deviceId}>{x.label}</option>)}</select></label><label>Micro<select value={mic} onChange={e=>setMic(e.target.value)}>{mics.map(x=><option key={x.deviceId} value={x.deviceId}>{x.label}</option>)}</select></label><div className="micMeter"><span>Niveau du micro</span><div><i style={{width:`${level}%`}}/></div></div><div className="mediaButtons"><button onClick={()=>setMicOn(v=>!v)}>{micOn?'🎙️ Micro activé':'🔇 Micro coupé'}</button><button onClick={()=>setCamOn(v=>!v)}>{camOn?'📹 Caméra activée':'🚫 Caméra coupée'}</button></div><button className="mediaStart" onClick={live?stop:connect}>{live?'Quitter la salle Realtime':'Entrer dans la salle Realtime'}</button><button onClick={start}>Tester seulement mes appareils</button><p className="mediaStatus">{status}</p><small>{live?'Tes pistes audio et vidéo sont maintenant publiées dans Cloudflare Realtime.':'Le test reste local; Entrer dans la salle publie réellement caméra et micro.'}</small></div></div></div>;
}
