'use client';
import {useEffect,useRef,useState} from 'react';

type Device={deviceId:string;label:string};
export default function MediaPreflight(){
 const videoRef=useRef<HTMLVideoElement>(null),streamRef=useRef<MediaStream|null>(null);
 const[cameras,setCameras]=useState<Device[]>([]),[mics,setMics]=useState<Device[]>([]),[camera,setCamera]=useState(''),[mic,setMic]=useState(''),[camOn,setCamOn]=useState(true),[micOn,setMicOn]=useState(true),[status,setStatus]=useState('Prêt à tester la caméra et le micro.'),[level,setLevel]=useState(0);
 async function loadDevices(){const d=await navigator.mediaDevices.enumerateDevices();const cs=d.filter(x=>x.kind==='videoinput').map((x,i)=>({deviceId:x.deviceId,label:x.label||`Caméra ${i+1}`}));const ms=d.filter(x=>x.kind==='audioinput').map((x,i)=>({deviceId:x.deviceId,label:x.label||`Micro ${i+1}`}));setCameras(cs);setMics(ms);if(!camera&&cs[0])setCamera(cs[0].deviceId);if(!mic&&ms[0])setMic(ms[0].deviceId)}
 async function start(){try{stop();setStatus('Demande des permissions…');const stream=await navigator.mediaDevices.getUserMedia({video:camera?{deviceId:{exact:camera}}:true,audio:mic?{deviceId:{exact:mic},echoCancellation:true,noiseSuppression:true,autoGainControl:true}:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});streamRef.current=stream;if(videoRef.current)videoRef.current.srcObject=stream;stream.getVideoTracks().forEach(t=>t.enabled=camOn);stream.getAudioTracks().forEach(t=>t.enabled=micOn);await loadDevices();meter(stream);setStatus('Caméra et micro prêts.');}catch(e:any){setStatus(e?.name==='NotAllowedError'?'Permission refusée. Autorise la caméra et le micro dans le navigateur.':'Impossible d’ouvrir les appareils. Vérifie qu’ils ne sont pas utilisés ailleurs.')}}
 function stop(){streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;if(videoRef.current)videoRef.current.srcObject=null;setLevel(0)}
 function meter(stream:MediaStream){try{const Ctx=(window.AudioContext||(window as any).webkitAudioContext);const ctx=new Ctx(),src=ctx.createMediaStreamSource(stream),an=ctx.createAnalyser();an.fftSize=256;src.connect(an);const a=new Uint8Array(an.frequencyBinCount);const tick=()=>{if(streamRef.current!==stream){ctx.close();return}an.getByteFrequencyData(a);setLevel(Math.min(100,Math.round(a.reduce((s,v)=>s+v,0)/a.length)));requestAnimationFrame(tick)};tick()}catch{}}
 useEffect(()=>()=>stop(),[]);
 useEffect(()=>{streamRef.current?.getVideoTracks().forEach(t=>t.enabled=camOn)},[camOn]);useEffect(()=>{streamRef.current?.getAudioTracks().forEach(t=>t.enabled=micOn)},[micOn]);
 return <div className="mediaPreflight"><div className="viewTitle"><span>EVOO-FI · AUDIO / VIDÉO</span><h2>Préparer ma caméra et mon micro.</h2></div><div className="mediaPreflightGrid"><div className="mediaPreview"><video ref={videoRef} autoPlay muted playsInline/><div className="mediaPreviewBadge">APERÇU LOCAL · non diffusé</div></div><div className="mediaSetup"><label>Caméra<select value={camera} onChange={e=>setCamera(e.target.value)}>{cameras.map(x=><option key={x.deviceId} value={x.deviceId}>{x.label}</option>)}</select></label><label>Micro<select value={mic} onChange={e=>setMic(e.target.value)}>{mics.map(x=><option key={x.deviceId} value={x.deviceId}>{x.label}</option>)}</select></label><div className="micMeter"><span>Niveau du micro</span><div><i style={{width:`${level}%`}}/></div></div><div className="mediaButtons"><button onClick={()=>setMicOn(v=>!v)}>{micOn?'🎙️ Micro activé':'🔇 Micro coupé'}</button><button onClick={()=>setCamOn(v=>!v)}>{camOn?'📹 Caméra activée':'🚫 Caméra coupée'}</button></div><button className="mediaStart" onClick={start}>Tester mes appareils</button><p className="mediaStatus">{status}</p><small>Ce test reste dans ton navigateur. La connexion à la salle Realtime sera branchée à l’étape suivante.</small></div></div></div>;
}
