'use client';
import Link from 'next/link';import {useState} from 'react';import '../../portals.css';import './classroom.css';
type Mode='stage'|'class'|'interactions'|'notes'|'ai';
export default function Classroom(){const[mode,setMode]=useState<Mode>('stage');const[side,setSide]=useState(true);return <main className="classroom"><header className="classroomTop"><div><Link href="/trainer" className="classroomBack">← Portail formateur</Link><strong>ÉV<span>OO</span>T! <small>RÉGIE</small></strong></div><div className="classroomSession"><b>Découvrir ÉVOOT!</b><span>12 participants · Salle ouverte</span></div><div className="classroomClock">00:18:42 <button>•••</button></div></header><nav className="classroomModes"><ModeButton active={mode==='stage'} onClick={()=>setMode('stage')} icon="🎬" label="Scène"/><ModeButton active={mode==='class'} onClick={()=>setMode('class')} icon="👥" label="Classe"/><ModeButton active={mode==='interactions'} onClick={()=>setMode('interactions')} icon="✋" label="Interactions" badge="3"/><ModeButton active={mode==='notes'} onClick={()=>setMode('notes')} icon="📝" label="Notes"/><ModeButton active={mode==='ai'} onClick={()=>setMode('ai')} icon="✦" label="ÉVOOT AI"/></nav><div className={`classroomWorkspace mode-${mode} ${side?'withSide':''}`}><section className="classroomMain">{mode==='stage'&&<Stage/>}{mode==='class'&&<ClassGrid/>}{mode==='interactions'&&<Interactions/>}{mode==='notes'&&<Notes/>}{mode==='ai'&&<AI/>}</section>{side&&<aside className="classroomSide"><div className="sideHead"><span>COULISSES</span><button onClick={()=>setSide(false)}>×</button></div><div className="nextBlock"><small>MAINTENANT</small><strong>Ton premier réflexe</strong><p>Question Live · 4 min</p></div><div className="trainerNote"><small>NOTE FORMATEUR</small><p>Observe les réponses avant de relancer. Ne donne pas la « bonne » réponse trop rapidement.</p></div><div className="pulse"><div><small>POULS DE LA CLASSE</small><b>Ça suit bien</b></div><strong>84%</strong><div className="pulseBar"><i/></div><p>👍 8 &nbsp; 🤔 2 &nbsp; 🐌 1 &nbsp; ✋ 1</p></div><div className="upNext"><small>ENSUITE</small><strong>Discussion guidée</strong><p>6 min · Échange de groupe</p></div></aside>}</div><footer className="classroomControl"><button>← Précédent</button><button className="controlSoft" onClick={()=>setSide(!side)}>☰ Coulisses</button><button className="controlLive">● EN DIRECT</button><button className="controlSoft">▣ Projection</button><button className="controlNext">Suivant →</button></footer></main>}
function ModeButton(p:{active:boolean;onClick:()=>void;icon:string;label:string;badge?:string}){return <button className={p.active?'active':''} onClick={p.onClick}><i>{p.icon}</i>{p.label}{p.badge&&<b>{p.badge}</b>}</button>}
function Stage(){return <div className="stage"><div className="stageLabel">SCÈNE · QUESTION LIVE</div><h1>Un client hausse le ton et critique votre service devant d’autres clients.</h1><p>Quel est votre premier réflexe?</p><div className="stageAnswers"><div><b>A</b> Me justifier immédiatement <span>18%</span></div><div><b>B</b> Écouter et valider <span>55%</span></div><div><b>C</b> Appeler un gestionnaire <span>9%</span></div><div><b>D</b> Lui demander de se calmer <span>18%</span></div></div><div className="stageMeta"><span>11 / 12 réponses</span><button>Afficher les résultats</button></div></div>}
function ClassGrid(){return <div><div className="viewTitle"><span>CLASSE</span><h2>Votre groupe, maintenant.</h2></div><div className="cameraGrid">{['Marie','Alex','Samir','Joëlle','Mathieu','Sophie','Karim','Julie'].map((n,i)=><div className={`camera ${i===1?'speaking':''}`} key={n}><div className="fakeVideo">{n[0]}</div><span>{n}{i===3?' ✋':''}</span></div>)}</div></div>}
function Interactions(){return <div><div className="viewTitle"><span>INTERACTIONS</span><h2>Ce qui demande votre attention.</h2></div><div className="interactionList"><article><b>✋ Joëlle a levé la main</b><span>Il y a 20 sec.</span><button>Donner la parole</button></article><article><b>🔒 Question privée</b><p>« Est-ce que cette technique fonctionne aussi par courriel? »</p><button>Répondre</button></article><article><b>💬 Question publique</b><p>« Est-ce qu'on peut avoir un exemple concret? »</p><button>Afficher à la classe</button></article></div></div>}
function Notes(){return <div><div className="viewTitle"><span>MES NOTES</span><h2>Privé. Attaché à cette séance.</h2></div><textarea className="notesArea" placeholder="Écris ici… Exemple : revenir sur le cas de la réception après la pause."/><div className="noteHint">Les notes pourront être rattachées automatiquement au bloc actif et retrouvées après la séance.</div></div>}
function AI(){return <div><div className="viewTitle"><span>ÉVOOT AI</span><h2>Votre copilote pédagogique.</h2></div><div className="aiCard"><strong>Le groupe hésite davantage sur cette question.</strong><p>Deux participants indiquent « pas certain » et les réponses sont divisées. Une courte relance avant la discussion pourrait aider.</p><div><button>Proposer une relance</button><button>Créer une question de validation</button><button>Ignorer</button></div></div></div>}
