'use client';
import {FormEvent,useEffect,useState} from 'react';
import EvootUpload from '@/components/EvootUpload';
import BackButton from '@/components/BackButton';
import '../../portals.css';

type Org={id:string;name:string;type:string;status:string;brandingJson:string;members:number};
const initial={name:'',id:'',type:'BUSINESS',primaryColor:'#F7941D',secondaryColor:'#111111',logoUrl:'',timezone:'America/Toronto',locale:'fr-CA'};
export default function OrganizationsPage(){
 const [form,setForm]=useState(initial);const [items,setItems]=useState<Org[]>([]);const [message,setMessage]=useState('');const [saving,setSaving]=useState(false);
 const load=()=>fetch('/api/evoot-admin/organizations',{cache:'no-store'}).then(r=>r.status===401?(window.location.href='/login',null):r.json()).then(v=>v?.ok&&setItems(v.organizations));
 useEffect(()=>{load()},[]);const set=(key:string,value:string)=>setForm(v=>({...v,[key]:value}));
 async function submit(e:FormEvent){e.preventDefault();setSaving(true);setMessage('');const r=await fetch('/api/evoot-admin/organizations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const v=await r.json();setSaving(false);if(!r.ok){setMessage(v.error||'Erreur');return}setForm(initial);setMessage('Organisation créée avec succès.');load();}
 return <main className="portal orgPage"><div className="portalShell">
  <div className="orgNav"><BackButton fallback="/evoot-admin" className="orgBack"/><div className="portalBrand">ÉV<span>OO</span>T!</div></div>
  <div className="orgHero"><div><div className="portalRole">Administration ÉVOOT · Organisations</div><h1>Organisations</h1><p className="portalLead">Crée et personnalise les espaces de tes clients. Leur marque devant, EVOOT! derrière.</p></div><div className="orgCount"><strong>{items.length}</strong><span>organisation{items.length===1?'':'s'}</span></div></div>
  <form className="orgCreator" onSubmit={submit}>
   <div className="orgFormPanel"><div className="orgSectionTitle"><span>01</span><div><strong>Identité</strong><small>Informations principales de l’organisation</small></div></div>
    <div className="orgFields"><label className="orgField orgWide"><span>Nom de l’organisation</span><input required value={form.name} onChange={e=>set('name',e.target.value)} placeholder="Ex. Brigade dentaire"/></label><label className="orgField"><span>Identifiant</span><input value={form.id} onChange={e=>set('id',e.target.value)} placeholder="Créé automatiquement"/></label><label className="orgField"><span>Type</span><select value={form.type} onChange={e=>set('type',e.target.value)}><option value="BUSINESS">Entreprise</option><option value="SCHOOL">École</option><option value="ORGANIZATION">Organisation / OBNL</option></select></label></div>
    <div className="orgDivider"/><div className="orgSectionTitle"><span>02</span><div><strong>Identité visuelle</strong><small>Personnalisation de l’expérience client</small></div></div>
    <div className="orgBrandFields"><label className="orgColor"><span>Couleur principale</span><div><input type="color" value={form.primaryColor} onChange={e=>set('primaryColor',e.target.value)}/><code>{form.primaryColor}</code></div></label><label className="orgColor"><span>Couleur secondaire</span><div><input type="color" value={form.secondaryColor} onChange={e=>set('secondaryColor',e.target.value)}/><code>{form.secondaryColor}</code></div></label></div>
    <div className="orgUpload"><div><strong>Logo</strong><small>PNG, JPG, WebP ou SVG</small></div><EvootUpload purpose="ORGANIZATION_LOGO" accept="image/png,image/jpeg,image/webp,image/svg+xml" label={form.logoUrl?'Remplacer':'Téléverser'} onUploaded={upload=>set('logoUrl',upload.url)}/>{form.logoUrl&&<button type="button" className="orgRemove" onClick={()=>set('logoUrl','')}>Retirer</button>}</div>
   </div>
   <aside className="orgPreviewPanel"><div className="orgPreviewLabel">APERÇU EN DIRECT</div><div className="orgPreview" style={{background:form.secondaryColor}}><div className="orgPreviewLogo">{form.logoUrl?<img src={form.logoUrl} alt="Logo"/>:<div style={{borderColor:form.primaryColor,color:form.primaryColor}}>{(form.name||'O').slice(0,1).toUpperCase()}</div>}</div><div><small>BIENVENUE CHEZ</small><h2 style={{color:form.primaryColor}}>{form.name||'Votre organisation'}</h2><p>Votre espace de formation</p></div><div className="orgPreviewFooter">Propulsé par <b>ÉV<span>OO</span>T!</b></div></div><button className="orgCreate" disabled={saving}>{saving?'Création en cours…':'Créer l’organisation →'}</button>{message&&<p className="orgMessage">{message}</p>}</aside>
  </form>
  <section className="orgList"><div className="orgListHead"><div><div className="portalRole">ESPACE CLIENTS</div><h2>Organisations existantes</h2></div></div><div className="orgCards">{items.length===0?<div className="orgEmpty">Aucune organisation pour le moment.</div>:items.map(o=>{let b:any={};try{b=JSON.parse(o.brandingJson||'{}')}catch{}return <article className="orgCard" key={o.id}><div className="orgCardAccent" style={{background:b.primaryColor||'#F7941D'}}/><div className="orgCardLogo" style={{background:b.secondaryColor||'#111'}}>{b.logoUrl?<img src={b.logoUrl} alt=""/>:<span style={{color:b.primaryColor||'#F7941D'}}>{o.name.slice(0,1).toUpperCase()}</span>}</div><div className="orgCardInfo"><div className="orgCardTop"><strong>{o.name}</strong><span className={o.status==='ACTIVE'?'isActive':''}>{o.status}</span></div><p>{o.type==='BUSINESS'?'Entreprise':o.type==='SCHOOL'?'École':'Organisation'} · {o.members} membre{o.members===1?'':'s'}</p><small>{o.id}</small></div><button type="button" className="orgManage">Gérer →</button></article>})}</div></section>
 </div></main>;
}
