'use client';

import Link from 'next/link';
import { FormEvent, useEffect, useState } from 'react';

const question = { prompt:'Un client arrive très fâché. Ton premier réflexe?', answers:['Lancer mon café au client','Aller pleurer dans le backstore','Lui expliquer immédiatement pourquoi il a tort','Prendre une pause et écouter activement'] };

export default function JoinPage() {
  const [code,setCode]=useState(''); const [name,setName]=useState(''); const [jobTitle,setJobTitle]=useState('');
  const [participantId,setParticipantId]=useState<number|null>(null); const [state,setState]=useState('LOBBY'); const [error,setError]=useState(''); const [joining,setJoining]=useState(false);
  const [selectedAnswer,setSelectedAnswer]=useState<number|null>(null); const [answering,setAnswering]=useState(false);
  useEffect(()=>{const value=new URLSearchParams(window.location.search).get('code')||'';setCode(value.replace(/\D/g,'').slice(0,6));},[]);
  useEffect(()=>{if(!participantId)return; const poll=async()=>{try{const r=await fetch(`/api/sessions/${code}`,{cache:'no-store'});if(r.ok){const d=await r.json();setState(d.session.state);}}catch{}};poll();const id=setInterval(poll,1500);return()=>clearInterval(id);},[participantId,code]);
  async function submit(e:FormEvent){e.preventDefault();setJoining(true);setError('');try{const r=await fetch(`/api/sessions/${code}/join`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,jobTitle})});const d=await r.json();if(!r.ok)throw new Error(d.error);setParticipantId(Number(d.participantId));setState(d.state);}catch(err){setError(err instanceof Error?err.message:'Impossible de rejoindre la séance.');setJoining(false);}}
  async function answer(answerIndex:number){if(!participantId||answering)return;setAnswering(true);setError('');try{const r=await fetch(`/api/sessions/${code}/answer`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({participantId,questionIndex:0,answerIndex})});const d=await r.json();if(!r.ok)throw new Error(d.error);setSelectedAnswer(answerIndex);}catch(err){setError(err instanceof Error?err.message:'Impossible d’enregistrer la réponse.');}finally{setAnswering(false);}}
  if(participantId){return <main className="participantPage"><section className="participantCard"><div className="brand">ÉV<span>OO</span>T!</div><div className="eyebrow">SÉANCE {code}</div>{state==='LOBBY'?<><h1>Tu es connecté.</h1><p><strong>{name}</strong> · {jobTitle}</p><div className="waitingPulse">En attente du formateur…</div><p className="participantHint">La prochaine question apparaîtra ici automatiquement.</p></>:<><div className="questionProgress">QUESTION 1 · TON RÉFLEXE</div><h1>{question.prompt}</h1><div className="participantAnswers">{question.answers.map((a,i)=><button key={i} disabled={answering} onClick={()=>answer(i)} aria-pressed={selectedAnswer===i}>{selectedAnswer===i?'✓ ':''}{a}</button>)}</div>{selectedAnswer!==null&&<p className="participantHint">Réponse enregistrée ✓ Tu peux la modifier tant que la question est ouverte.</p>}{error&&<p>{error}</p>}</>}</section><footer>Propulsé par ÉVOOT — Évolution PME, créateur de marques.</footer></main>}
  return <main className="participantPage"><section className="participantCard"><Link className="brand" href="/">ÉV<span>OO</span>T!</Link><div className="eyebrow">REJOINDRE UNE FORMATION</div><h1>Entre dans la séance.</h1><p>Pas de compte. Ton nom, ton poste, pis c’est parti.</p><form className="participantForm" onSubmit={submit}><label>Code de séance<input inputMode="numeric" maxLength={6} placeholder="000000" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))}/></label><label>Nom<input autoComplete="name" placeholder="Ton nom" value={name} onChange={e=>setName(e.target.value)}/></label><label>Titre du poste<input placeholder="Ex. Hygiéniste dentaire" value={jobTitle} onChange={e=>setJobTitle(e.target.value)}/></label>{error&&<p>{error}</p>}<button className="primary" disabled={joining||code.length!==6||!name.trim()||!jobTitle.trim()}>{joining?'Connexion…':'Rejoindre'}</button></form></section><footer>Propulsé par ÉVOOT — Évolution PME, créateur de marques.</footer></main>;
}
