'use client';
import Link from 'next/link';import {FormEvent,useCallback,useEffect,useRef,useState} from 'react';import RealtimeClassroom from '../trainer/classroom/RealtimeClassroom';
type Block={type:string;title:string;content:Record<string,any>;visibility:string};
export default function JoinPage(){
 const[code,setCode]=useState('');const[name,setName]=useState('');const[jobTitle,setJobTitle]=useState('');const[participantId,setParticipantId]=useState<number|null>(null);const[state,setState]=useState('LOBBY');const[block,setBlock]=useState<Block|null>(null);const[questionIndex,setQuestionIndex]=useState(-1);const[error,setError]=useState('');const[joining,setJoining]=useState(false);const[selectedAnswer,setSelectedAnswer]=useState<number|null>(null);const[answering,setAnswering]=useState(false);const[videoOpen,setVideoOpen]=useState(true);const lastVersion=useRef('');const liveVersion=useRef(0);const syncing=useRef(false);
 useEffect(()=>{setCode((new URLSearchParams(window.location.search).get('code')||'').replace(/\D/g,'').slice(0,6))},[]);
 const sync=useCallback(async()=>{if(!participantId||!code||syncing.current)return;syncing.current=true;try{const r=await fetch(`/api/sessions/${code}?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)return;const d=await r.json();const next=Number(d.session.current_question||0);const version=`${d.session.state}:${next}:${d.currentQuestionIndex??-1}`;if(version!==lastVersion.current){lastVersion.current=version;setSelectedAnswer(null)}setState(d.session.state);setQuestionIndex(Number(d.currentQuestionIndex??-1));const b=d.currentBlock as Block|null;setBlock(b&&b.visibility!=='TRAINER'?b:null)}catch{}finally{syncing.current=false}},[participantId,code]);
 const checkLive=useCallback(async()=>{if(!participantId||!code)return;try{const r=await fetch(`/api/realtime/live-sync?roomId=${encodeURIComponent(code)}&after=${liveVersion.current}&t=${Date.now()}`,{cache:'no-store'});if(!r.ok)return;const d=await r.json();if(d.event){liveVersion.current=Number(d.event.version||Date.now());await sync()}}catch{}},[participantId,code,sync]);
 useEffect(()=>{if(!participantId)return;sync();checkLive();const liveId=setInterval(checkLive,250);const fallbackId=setInterval(sync,2500);let channel:BroadcastChannel|null=null;try{channel=new BroadcastChannel(`evoot-live-${code}`);channel.onmessage=()=>sync()}catch{}const onVisible=()=>{if(document.visibilityState==='visible'){checkLive();sync()}};const onStorage=(e:StorageEvent)=>{if(e.key===`evoot-live-${code}`)sync()};window.addEventListener('focus',onVisible);window.addEventListener('storage',onStorage);document.addEventListener('visibilitychange',onVisible);return()=>{clearInterval(liveId);clearInterval(fallbackId);channel?.close();window.removeEventListener('focus',onVisible);window.removeEventListener('storage',onStorage);document.removeEventListener('visibilitychange',onVisible)}},[participantId,code,sync,checkLive]);
 async function submit(e:FormEvent){e.preventDefault();setJoining(true);setError('');try{const r=await fetch(`/api/sessions/${code}/join`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,jobTitle})});const d=await r.json();if(!r.ok)throw new Error(d.error);setParticipantId(Number(d.participantId));setState(d.state)}catch(e){setError(e instanceof Error?e.message:'Impossible de rejoindre la séance.');setJoining(false)}}
 async function answer(i:number){if(!participantId||answering||questionIndex<0)return;setAnswering(true);try{const r=await fetch(`/api/sessions/${code}/answer`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({participantId,questionIndex,answerIndex:i})});const d=await r.json();if(!r.ok)throw new Error(d.error);setSelectedAnswer(i)}catch(e){setError(e instanceof Error?e.message:'Impossible d’enregistrer la réponse.')}finally{setAnswering(false)}}
 if(participantId&&state==='LOBBY')return <main className="participantPage"><section className="participantCard"><div className="brand">ÉV<span>OO</span>T!</div><div className="eyebrow">SALLE D’ATTENTE · {code}</div><h1>Bienvenue, {name}.</h1><p>Tu es bien connecté à la formation.</p><div style={{margin:'28px 0',padding:24,border:'1px solid #333',borderRadius:18,background:'#111'}}><div className="waitingPulse">● En attente du formateur…</div><p style={{opacity:.7,marginBottom:0}}>La séance commencera automatiquement dès que le formateur lancera le LIVE.</p></div><p style={{fontSize:14,opacity:.6}}>Tu peux garder cette page ouverte. Rien d’autre à faire.</p></section><footer>Propulsé par ÉVOOT — Évolution PME, créateur de marques.</footer></main>;
 if(participantId)return <main className="participantPage"><section className="participantCard" style={videoOpen?{maxWidth:1100}:undefined}><div className="brand">ÉV<span>OO</span>T!</div><div className="eyebrow">LIVE · {code}</div><button className="secondary" style={{marginBottom:18}} onClick={()=>setVideoOpen(v=>!v)}>{videoOpen?'Masquer la classe vidéo':'🎥 Afficher la classe vidéo'}</button>{videoOpen&&<div style={{textAlign:'left',marginBottom:24}}><RealtimeClassroom roomId={code} identity={`learner-${participantId}`} role="learner"/></div>}{state==='FINISHED'?<><h1>Merci!</h1><p>La formation est terminée.</p></>:!block?<><h1>Le formateur prépare la suite.</h1><div className="waitingPulse">La prochaine activité arrive ici…</div></>:block.type==='LIVE_QUESTION'?<><div className="questionProgress">QUESTION LIVE</div><h1>{block.content.prompt||block.title}</h1><div className="participantAnswers">{(block.content.answers||[]).map((a:string,i:number)=><button key={i} disabled={answering} onClick={()=>answer(i)} aria-pressed={selectedAnswer===i}>{selectedAnswer===i?'✓ ':''}{a}</button>)}</div>{selectedAnswer!==null&&<p className="participantHint">Réponse enregistrée ✓</p>}</>:<><div className="questionProgress">{block.type.replace('_',' ')}</div><h1>{block.title}</h1>{block.content.text&&<p>{block.content.text}</p>}{block.type==='IMAGE'&&block.content.url&&<img style={{maxWidth:'100%',borderRadius:12}} src={block.content.url} alt={block.title}/>}<div className="waitingPulse">Suis le formateur…</div></>}{error&&<p>{error}</p>}</section><footer>Propulsé par ÉVOOT — Évolution PME, créateur de marques.</footer></main>;
 return <main className="participantPage"><section className="participantCard"><Link className="brand" href="/">ÉV<span>OO</span>T!</Link><div className="eyebrow">REJOINDRE UNE FORMATION</div><h1>Entre dans la séance.</h1><p>Pas de compte. Ton nom, ton poste, pis c’est parti.</p><form className="participantForm" onSubmit={submit}><label>Code de séance<input inputMode="numeric" maxLength={6} placeholder="000000" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))}/></label><label>Nom<input autoComplete="name" placeholder="Ton nom" value={name} onChange={e=>setName(e.target.value)}/></label><label>Titre du poste<input placeholder="Ex. Hygiéniste dentaire" value={jobTitle} onChange={e=>setJobTitle(e.target.value)}/></label>{error&&<p>{error}</p>}<button className="primary" disabled={joining||code.length!==6||!name.trim()||!jobTitle.trim()}>{joining?'Connexion…':'Rejoindre'}</button></form></section><footer>Propulsé par ÉVOOT — Évolution PME, créateur de marques.</footer></main>}
