import {NextResponse} from 'next/server';
import {getDB} from '@/lib/db';
import {requireOrganizationRole} from '@/lib/auth';

function unauthorized(e:unknown){return e instanceof Error&&e.message==='UNAUTHORIZED'}

export async function GET(){try{const auth=await requireOrganizationRole('ORG_ADMIN');const org=auth.organizationId!;const db=getDB();const [cohorts,trainings]=await Promise.all([db.prepare(`SELECT c.id,c.name,c.training_id trainingId,c.status,c.starts_at startsAt,c.ends_at endsAt,t.title trainingTitle,COUNT(cm.id) memberCount FROM cohorts c JOIN trainings t ON t.id=c.training_id AND t.organization_id=c.organization_id LEFT JOIN cohort_members cm ON cm.cohort_id=c.id AND cm.role='LEARNER' AND cm.status='ACTIVE' WHERE c.organization_id=? GROUP BY c.id ORDER BY c.created_at DESC`).bind(org).all(),db.prepare(`SELECT id,title FROM trainings WHERE organization_id=? ORDER BY title`).bind(org).all()]);return NextResponse.json({cohorts:cohorts.results||[],trainings:trainings.results||[]})}catch(e){if(unauthorized(e))return NextResponse.json({error:'Non autorisé'},{status:401});return NextResponse.json({error:'Impossible de charger les groupes'},{status:500})}}
export async function POST(req:Request){try{const auth=await requireOrganizationRole('ORG_ADMIN');const org=auth.organizationId!;const b=await req.json();const name=String(b.name||'').trim();const trainingId=Number(b.trainingId);if(!name||!trainingId)return NextResponse.json({error:'Nom et formation requis'},{status:400});const db=getDB();const training=await db.prepare('SELECT id FROM trainings WHERE id=? AND organization_id=?').bind(trainingId,org).first();if(!training)return NextResponse.json({error:'Formation introuvable'},{status:404});await db.prepare(`INSERT INTO cohorts (organization_id,training_id,name,status,starts_at,ends_at) VALUES (?,?,?,'ACTIVE',?,?)`).bind(org,trainingId,name,b.startsAt?String(b.startsAt):null,b.endsAt?String(b.endsAt):null).run();return NextResponse.json({ok:true},{status:201})}catch(e){if(unauthorized(e))return NextResponse.json({error:'Non autorisé'},{status:401});return NextResponse.json({error:'Impossible de créer le groupe'},{status:500})}}
export async function DELETE(req:Request){try{const auth=await requireOrganizationRole('ORG_ADMIN');const org=auth.organizationId!;const b=await req.json().catch(()=>({}));const id=Number(b.id);if(!id)return NextResponse.json({error:'Groupe invalide'},{status:400});const db=getDB();const cohort=await db.prepare('SELECT id FROM cohorts WHERE id=? AND organization_id=?').bind(id,org).first();if(!cohort)return NextResponse.json({error:'Groupe introuvable'},{status:404});const scheduled=await db.prepare(`SELECT COUNT(*) n FROM course_sessions WHERE organization_id=? AND cohort_id=? AND status NOT IN ('CANCELLED','COMPLETED')`).bind(org,id).first<{n:number}>();if((scheduled?.n||0)>0)return NextResponse.json({error:'Ce groupe a des séances actives ou planifiées. Supprimez ou terminez ces séances avant de supprimer le groupe.'},{status:409});await db.prepare('DELETE FROM cohorts WHERE id=? AND organization_id=?').bind(id,org).run();return NextResponse.json({ok:true})}catch(e){if(unauthorized(e))return NextResponse.json({error:'Non autorisé'},{status:401});return NextResponse.json({error:'Impossible de supprimer le groupe'},{status:500})}}
