'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import './join-code.css';

export default function Home(){
 const[code,setCode]=useState('');const router=useRouter();
 const digits=(code+'      ').slice(0,6).split('');
 return <main className="shell"><nav className="nav"><div className="brand">ÉV<span>OO</span>T!</div><Link className="ghost" href="/dashboard">Connexion entreprise</Link></nav><section className="hero"><div className="eyebrow">FORMATION INTERACTIVE EN DIRECT</div><h1>On apprend.<br/>On répond.<br/><em>On évolue.</em></h1><p className="lead">Des formations qui font participer pour vrai. ÉVOOT transforme les situations de travail en discussions, réflexions et apprentissages concrets.</p><div className="actions"><Link className="primary" href="/dashboard">Créer une séance live</Link><Link className="secondary" href="/dashboard">Créer mon organisation</Link></div></section><section className="join joinRedesign"><div className="joinIntro"><div className="eyebrow">PARTICIPANT</div><h2>Tu as un code?</h2><p>Entre le code affiché par ton formateur.<br/>Aucun compte requis.</p></div><form className="joinForm joinCodeForm" onSubmit={e=>{e.preventDefault();if(code.length===6)router.push(`/join?code=${code}`)}}><label className="joinCodeLabel" htmlFor="session-code"><span>ENTRE LE CODE À 6 CHIFFRES</span></label><div className="joinCodeBox"><div className="digitPreview" aria-hidden="true">{digits.map((d,i)=><span key={i}>{d.trim()?d:'0'}</span>)}</div><input id="session-code" className="joinCodeInput" aria-label="Code de séance à 6 chiffres" inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))}/></div><div className="joinCodeHint">ⓘ <span>Le code est composé de 6 chiffres.</span></div><button className="primary joinCodeButton" disabled={code.length!==6}>Rejoindre</button></form></section><section className="features"><article><strong>01</strong><h3>Ton réflexe</h3><p>On part de ce que les participants feraient spontanément.</p></article><article><strong>02</strong><h3>Et maintenant?</h3><p>On applique une nouvelle compétence à une situation concrète.</p></article><article><strong>03</strong><h3>Mets-le en pratique</h3><p>On observe ce qui a changé et ce qui est réellement compris.</p></article></section><footer>ÉVOOT! — Des compétences comportementales éprouvées, adaptées au quotidien professionnel.</footer></main>}
