export type TrainingToolCategory='structure'|'content'|'interaction'|'collaboration'|'facilitation';
export type TrainingToolVisibility='LIVE'|'SELF_PACED'|'BOTH'|'TRAINER';
export type PresentationSourceType='PPTX'|'PPT'|'PDF'|'GOOGLE_SLIDES'|'KEYNOTE_EXPORT'|'IMAGES';
export type TrainingToolType='SECTION'|'TEXT'|'IMAGE'|'VIDEO'|'PRESENTATION'|'ACTIVITY'|'SCENARIO'|'LIVE_QUESTION'|'DISCUSSION'|'TRAINER_NOTE'|'BREAK'|'WHITEBOARD'|'INTERACTIVE_BOOK';
export type TrainingToolFieldType='text'|'textarea'|'number'|'checkbox'|'select'|'url';
export type TrainingToolField={key:string;label:string;type:TrainingToolFieldType;placeholder?:string;options?:{value:string;label:string}[]};

export type TrainingToolDefinition={type:TrainingToolType;label:string;icon:string;category:TrainingToolCategory;description:string;defaultVisibility:TrainingToolVisibility;defaultContent:Record<string,unknown>;capabilities:{live:boolean;selfPaced:boolean;collaborative:boolean;trainerOnly:boolean};status:'active'|'foundation';fields?:TrainingToolField[]};
export type TrainingToolBlock={type:TrainingToolType;title:string;content:Record<string,unknown>;durationMinutes:number|null;visibility:TrainingToolVisibility};

export const PRESENTATION_SOURCE_TYPES:Record<PresentationSourceType,{label:string;accept:string;mode:'UPLOAD'|'LINK'}>={PPTX:{label:'PowerPoint (.pptx)',accept:'.pptx',mode:'UPLOAD'},PPT:{label:'PowerPoint ancien (.ppt)',accept:'.ppt',mode:'UPLOAD'},PDF:{label:'Présentation PDF',accept:'.pdf',mode:'UPLOAD'},GOOGLE_SLIDES:{label:'Google Slides',accept:'https://docs.google.com/presentation/',mode:'LINK'},KEYNOTE_EXPORT:{label:'Keynote exporté (PDF/PPTX)',accept:'.pdf,.pptx',mode:'UPLOAD'},IMAGES:{label:'Diapositives en images',accept:'.png,.jpg,.jpeg,.webp',mode:'UPLOAD'}};

export const TRAINING_TOOLS:Record<TrainingToolType,TrainingToolDefinition>={
SECTION:{type:'SECTION',label:'Section',icon:'§',category:'structure',description:'Structure une partie de la formation.',defaultVisibility:'BOTH',defaultContent:{intro:'',objective:''},capabilities:{live:true,selfPaced:true,collaborative:false,trainerOnly:false},status:'active'},
TEXT:{type:'TEXT',label:'Texte / contenu',icon:'T',category:'content',description:'Présente du contenu pédagogique.',defaultVisibility:'BOTH',defaultContent:{text:'',keyPoint:''},capabilities:{live:true,selfPaced:true,collaborative:false,trainerOnly:false},status:'active'},
IMAGE:{type:'IMAGE',label:'Image',icon:'▧',category:'content',description:'Présente une image avec contexte.',defaultVisibility:'BOTH',defaultContent:{url:'',caption:'',alt:''},capabilities:{live:true,selfPaced:true,collaborative:false,trainerOnly:false},status:'active'},
VIDEO:{type:'VIDEO',label:'Vidéo',icon:'▶',category:'content',description:'Présente une vidéo dans le scénario.',defaultVisibility:'BOTH',defaultContent:{url:'',intro:'',instructions:''},capabilities:{live:true,selfPaced:true,collaborative:false,trainerOnly:false},status:'active'},
PRESENTATION:{type:'PRESENTATION',label:'Présentation',icon:'▣',category:'content',description:'Lit PowerPoint, PDF, Google Slides et autres présentations directement dans EVOOT.',defaultVisibility:'BOTH',defaultContent:{resourceId:'',fileName:'',sourceUrl:'',sourceType:'PPTX',startSlide:1,syncSlide:true,showPresenterNotes:true,allowLearnerNavigation:false,fullscreenEnabled:true,preserveAnimations:true,autoAdvanceSeconds:null},capabilities:{live:true,selfPaced:true,collaborative:false,trainerOnly:false},status:'foundation',fields:[{key:'sourceType',label:'Format',type:'select',options:Object.entries(PRESENTATION_SOURCE_TYPES).map(([value,item])=>({value,label:item.label}))},{key:'sourceUrl',label:'Lien ou ressource',type:'url',placeholder:'Google Slides ou ressource importée'},{key:'startSlide',label:'Diapositive de départ',type:'number'},{key:'syncSlide',label:'Synchroniser la diapositive avec les participants',type:'checkbox'},{key:'showPresenterNotes',label:'Afficher les notes du présentateur',type:'checkbox'},{key:'allowLearnerNavigation',label:'Autoriser la navigation libre des participants',type:'checkbox'}]},
ACTIVITY:{type:'ACTIVITY',label:'Activité / exercice',icon:'✦',category:'interaction',description:'Guide une activité pédagogique.',defaultVisibility:'BOTH',defaultContent:{objective:'',instructions:'',materials:'',debrief:''},capabilities:{live:true,selfPaced:true,collaborative:true,trainerOnly:false},status:'active'},
SCENARIO:{type:'SCENARIO',label:'Scénario',icon:'◇',category:'interaction',description:'Met les participants en situation.',defaultVisibility:'BOTH',defaultContent:{context:'',situation:'',task:'',debrief:''},capabilities:{live:true,selfPaced:true,collaborative:true,trainerOnly:false},status:'active'},
LIVE_QUESTION:{type:'LIVE_QUESTION',label:'Question ÉVOOT Live',icon:'?',category:'interaction',description:'Question interactive lancée par le formateur.',defaultVisibility:'BOTH',defaultContent:{prompt:'Nouvelle question',answers:['Réponse A','Réponse B','Réponse C','Réponse D'],why:'',relances:['','','']},capabilities:{live:true,selfPaced:true,collaborative:false,trainerOnly:false},status:'active'},
DISCUSSION:{type:'DISCUSSION',label:'Discussion',icon:'☵',category:'interaction',description:'Anime une discussion guidée.',defaultVisibility:'BOTH',defaultContent:{prompt:'',relances:['','',''],takeaway:''},capabilities:{live:true,selfPaced:false,collaborative:true,trainerOnly:false},status:'active'},
TRAINER_NOTE:{type:'TRAINER_NOTE',label:'Notes formateur',icon:'✎',category:'facilitation',description:'Repère privé pour le formateur.',defaultVisibility:'TRAINER',defaultContent:{note:'',cue:''},capabilities:{live:true,selfPaced:false,collaborative:false,trainerOnly:true},status:'active'},
BREAK:{type:'BREAK',label:'Pause',icon:'Ⅱ',category:'facilitation',description:'Insère une pause dans le déroulement.',defaultVisibility:'BOTH',defaultContent:{message:'',instructions:''},capabilities:{live:true,selfPaced:true,collaborative:false,trainerOnly:false},status:'active'},
WHITEBOARD:{type:'WHITEBOARD',label:'Tableau blanc',icon:'□',category:'collaboration',description:'Tableau pédagogique formateur ou collaboratif.',defaultVisibility:'LIVE',defaultContent:{instructions:'',mode:'TRAINER_ONLY',template:'BLANK'},capabilities:{live:true,selfPaced:false,collaborative:true,trainerOnly:false},status:'foundation',fields:[{key:'instructions',label:'Consignes',type:'textarea',placeholder:'Ce que les participants doivent faire sur le tableau…'},{key:'mode',label:'Mode',type:'select',options:[{value:'TRAINER_ONLY',label:'Formateur seulement'},{value:'COLLABORATIVE',label:'Collaboratif'}]},{key:'template',label:'Fond de départ',type:'select',options:[{value:'BLANK',label:'Tableau vide'},{value:'PREPARED',label:'Tableau préparé'}]}]},
INTERACTIVE_BOOK:{type:'INTERACTIVE_BOOK',label:'Livre interactif',icon:'▤',category:'content',description:'Manuel interactif annotable et synchronisable pendant la formation.',defaultVisibility:'BOTH',defaultContent:{resourceId:'',instructions:'',startPage:1,syncPage:true,allowLearnerAnnotations:false},capabilities:{live:true,selfPaced:true,collaborative:true,trainerOnly:false},status:'foundation',fields:[{key:'resourceId',label:'Manuel / ressource',type:'text',placeholder:'Ressource importée'},{key:'instructions',label:'Consignes',type:'textarea'},{key:'startPage',label:'Page de départ',type:'number'},{key:'syncPage',label:'Synchroniser la page du formateur',type:'checkbox'},{key:'allowLearnerAnnotations',label:'Autoriser les annotations des participants',type:'checkbox'}]}
};

export const TRAINING_TOOL_TYPES=Object.keys(TRAINING_TOOLS) as TrainingToolType[];
export const TRAINING_TOOL_PALETTE=TRAINING_TOOL_TYPES.map(type=>TRAINING_TOOLS[type]);
export const getTrainingTool=(type:TrainingToolType)=>TRAINING_TOOLS[type];
const cloneContent=(content:Record<string,unknown>)=>JSON.parse(JSON.stringify(content)) as Record<string,unknown>;
export const createTrainingToolBlock=(type:TrainingToolType):TrainingToolBlock=>{const tool=getTrainingTool(type);return {type,title:tool.label,content:cloneContent(tool.defaultContent),durationMinutes:null,visibility:tool.defaultVisibility};};
export const hydrateTrainingToolBlock=(block:TrainingToolBlock):TrainingToolBlock=>{const tool=getTrainingTool(block.type);return {...block,title:block.title||tool.label,content:{...cloneContent(tool.defaultContent),...(block.content||{})},visibility:block.visibility||tool.defaultVisibility};};
