export type TrainingToolCategory='structure'|'content'|'interaction'|'collaboration'|'facilitation';
export type TrainingToolVisibility='LIVE'|'SELF_PACED'|'BOTH'|'TRAINER';
export type PresentationSourceType='PPTX'|'PPT'|'PDF'|'GOOGLE_SLIDES'|'KEYNOTE_EXPORT'|'IMAGES';
export type TrainingToolType='SECTION'|'TEXT'|'IMAGE'|'VIDEO'|'PRESENTATION'|'DOCUMENT'|'ACTIVITY'|'SCENARIO'|'LIVE_QUESTION'|'OPEN_QUESTION'|'POLL'|'WORD_CLOUD'|'RANKING'|'DISCUSSION'|'TEAM_WORK'|'INDIVIDUAL_EXERCISE'|'FILE_SUBMISSION'|'TRAINER_NOTE'|'BREAK'|'TIMER'|'WHITEBOARD'|'INTERACTIVE_BOOK';
export type TrainingToolFieldType='text'|'textarea'|'number'|'checkbox'|'select'|'url';
export type TrainingToolField={key:string;label:string;type:TrainingToolFieldType;placeholder?:string;options?:{value:string;label:string}[]};
export type TrainingToolDefinition={type:TrainingToolType;label:string;icon:string;category:TrainingToolCategory;description:string;defaultVisibility:TrainingToolVisibility;defaultContent:Record<string,unknown>;capabilities:{live:boolean;selfPaced:boolean;collaborative:boolean;trainerOnly:boolean};status:'active'|'foundation';fields?:TrainingToolField[]};
export type TrainingToolBlock={type:TrainingToolType;title:string;content:Record<string,unknown>;durationMinutes:number|null;visibility:TrainingToolVisibility};

export const PRESENTATION_SOURCE_TYPES:Record<PresentationSourceType,{label:string;accept:string;mode:'UPLOAD'|'LINK'}>={PPTX:{label:'PowerPoint (.pptx)',accept:'.pptx',mode:'UPLOAD'},PPT:{label:'PowerPoint ancien (.ppt)',accept:'.ppt',mode:'UPLOAD'},PDF:{label:'Présentation PDF',accept:'.pdf',mode:'UPLOAD'},GOOGLE_SLIDES:{label:'Google Slides',accept:'https://docs.google.com/presentation/',mode:'LINK'},KEYNOTE_EXPORT:{label:'Keynote exporté (PDF/PPTX)',accept:'.pdf,.pptx',mode:'UPLOAD'},IMAGES:{label:'Diapositives en images',accept:'.png,.jpg,.jpeg,.webp',mode:'UPLOAD'}};
const options=(values:[string,string][])=>values.map(([value,label])=>({value,label}));
const cap=(live:boolean,selfPaced:boolean,collaborative=false,trainerOnly=false)=>({live,selfPaced,collaborative,trainerOnly});

export const TRAINING_TOOLS:Record<TrainingToolType,TrainingToolDefinition>={
SECTION:{type:'SECTION',label:'Section',icon:'§',category:'structure',description:'Structure une partie de la formation.',defaultVisibility:'BOTH',defaultContent:{intro:'',objective:''},capabilities:cap(true,true),status:'active'},
TEXT:{type:'TEXT',label:'Texte / contenu',icon:'T',category:'content',description:'Présente du contenu pédagogique.',defaultVisibility:'BOTH',defaultContent:{text:'',keyPoint:''},capabilities:cap(true,true),status:'active'},
IMAGE:{type:'IMAGE',label:'Image',icon:'▧',category:'content',description:'Présente une image avec contexte.',defaultVisibility:'BOTH',defaultContent:{url:'',caption:'',alt:''},capabilities:cap(true,true),status:'active'},
VIDEO:{type:'VIDEO',label:'Vidéo',icon:'▶',category:'content',description:'Présente une vidéo dans le scénario.',defaultVisibility:'BOTH',defaultContent:{url:'',intro:'',instructions:''},capabilities:cap(true,true),status:'active'},
PRESENTATION:{type:'PRESENTATION',label:'Présentation',icon:'▣',category:'content',description:'Lit PowerPoint, PDF, Google Slides et autres présentations directement dans EVOOT.',defaultVisibility:'BOTH',defaultContent:{resourceId:'',fileName:'',sourceUrl:'',sourceType:'PPTX',startSlide:1,syncSlide:true,showPresenterNotes:true,allowLearnerNavigation:false,fullscreenEnabled:true,preserveAnimations:true,autoAdvanceSeconds:null},capabilities:cap(true,true),status:'foundation',fields:[{key:'sourceType',label:'Format',type:'select',options:Object.entries(PRESENTATION_SOURCE_TYPES).map(([value,item])=>({value,label:item.label}))},{key:'sourceUrl',label:'Lien ou ressource',type:'url',placeholder:'Google Slides ou ressource importée'},{key:'startSlide',label:'Diapositive de départ',type:'number'},{key:'syncSlide',label:'Synchroniser la diapositive avec les participants',type:'checkbox'},{key:'showPresenterNotes',label:'Afficher les notes du présentateur',type:'checkbox'},{key:'allowLearnerNavigation',label:'Autoriser la navigation libre des participants',type:'checkbox'}]},
DOCUMENT:{type:'DOCUMENT',label:'Document / PDF',icon:'▥',category:'content',description:'Affiche un document de référence dans le déroulement.',defaultVisibility:'BOTH',defaultContent:{resourceId:'',sourceUrl:'',instructions:'',startPage:1,syncPage:true},capabilities:cap(true,true),status:'foundation',fields:[{key:'sourceUrl',label:'Document / ressource',type:'url',placeholder:'PDF ou ressource importée'},{key:'instructions',label:'Consignes',type:'textarea'},{key:'startPage',label:'Page de départ',type:'number'},{key:'syncPage',label:'Synchroniser la page',type:'checkbox'}]},
ACTIVITY:{type:'ACTIVITY',label:'Activité / exercice',icon:'✦',category:'interaction',description:'Guide une activité pédagogique.',defaultVisibility:'BOTH',defaultContent:{objective:'',instructions:'',materials:'',debrief:''},capabilities:cap(true,true,true),status:'active'},
SCENARIO:{type:'SCENARIO',label:'Scénario',icon:'◇',category:'interaction',description:'Met les participants en situation.',defaultVisibility:'BOTH',defaultContent:{context:'',situation:'',task:'',debrief:''},capabilities:cap(true,true,true),status:'active'},
LIVE_QUESTION:{type:'LIVE_QUESTION',label:'Question ÉVOOT Live',icon:'?',category:'interaction',description:'Question interactive lancée par le formateur.',defaultVisibility:'BOTH',defaultContent:{prompt:'Nouvelle question',answers:['Réponse A','Réponse B','Réponse C','Réponse D'],why:'',relances:['','','']},capabilities:cap(true,true),status:'active'},
OPEN_QUESTION:{type:'OPEN_QUESTION',label:'Question ouverte',icon:'¿',category:'interaction',description:'Recueille une réponse libre de chaque participant.',defaultVisibility:'BOTH',defaultContent:{prompt:'',instructions:'',anonymous:false,showResponses:true},capabilities:cap(true,true,true),status:'foundation',fields:[{key:'prompt',label:'Question',type:'textarea',placeholder:'Pose une question ouverte…'},{key:'instructions',label:'Consignes',type:'textarea'},{key:'anonymous',label:'Réponses anonymes',type:'checkbox'},{key:'showResponses',label:'Afficher les réponses au groupe',type:'checkbox'}]},
POLL:{type:'POLL',label:'Sondage',icon:'◉',category:'interaction',description:'Prend rapidement le pouls du groupe.',defaultVisibility:'BOTH',defaultContent:{prompt:'',options:'Option 1\nOption 2',multiple:false,anonymous:true},capabilities:cap(true,true,true),status:'foundation',fields:[{key:'prompt',label:'Question du sondage',type:'textarea'},{key:'options',label:'Choix (un par ligne)',type:'textarea'},{key:'multiple',label:'Choix multiples',type:'checkbox'},{key:'anonymous',label:'Réponses anonymes',type:'checkbox'}]},
WORD_CLOUD:{type:'WORD_CLOUD',label:'Nuage de mots',icon:'☁',category:'interaction',description:'Transforme les réponses courtes du groupe en nuage de mots.',defaultVisibility:'LIVE',defaultContent:{prompt:'',maxWords:3,anonymous:true},capabilities:cap(true,false,true),status:'foundation',fields:[{key:'prompt',label:'Question',type:'textarea'},{key:'maxWords',label:'Mots maximum par participant',type:'number'},{key:'anonymous',label:'Réponses anonymes',type:'checkbox'}]},
RANKING:{type:'RANKING',label:'Classement / priorisation',icon:'≡',category:'interaction',description:'Fait classer des options par ordre de priorité.',defaultVisibility:'BOTH',defaultContent:{prompt:'',items:'Élément 1\nÉlément 2\nÉlément 3',showAggregate:true},capabilities:cap(true,true,true),status:'foundation',fields:[{key:'prompt',label:'Consigne',type:'textarea'},{key:'items',label:'Éléments à classer (un par ligne)',type:'textarea'},{key:'showAggregate',label:'Afficher le classement du groupe',type:'checkbox'}]},
DISCUSSION:{type:'DISCUSSION',label:'Discussion',icon:'☵',category:'interaction',description:'Anime une discussion guidée.',defaultVisibility:'BOTH',defaultContent:{prompt:'',relances:['','',''],takeaway:''},capabilities:cap(true,false,true),status:'active'},
TEAM_WORK:{type:'TEAM_WORK',label:'Travail d’équipe',icon:'👥',category:'collaboration',description:'Envoie les participants travailler en équipes puis les ramène en groupe.',defaultVisibility:'LIVE',defaultContent:{instructions:'',teamSize:3,durationMinutes:10,deliverable:'',autoReturn:true},capabilities:cap(true,false,true),status:'foundation',fields:[{key:'instructions',label:'Consignes aux équipes',type:'textarea'},{key:'teamSize',label:'Participants par équipe',type:'number'},{key:'durationMinutes',label:'Durée',type:'number'},{key:'deliverable',label:'Livrable attendu',type:'textarea'},{key:'autoReturn',label:'Retour automatique en classe',type:'checkbox'}]},
INDIVIDUAL_EXERCISE:{type:'INDIVIDUAL_EXERCISE',label:'Exercice individuel',icon:'◎',category:'interaction',description:'Donne une tâche individuelle avec consignes et durée.',defaultVisibility:'BOTH',defaultContent:{instructions:'',durationMinutes:5,responseRequired:false},capabilities:cap(true,true),status:'foundation',fields:[{key:'instructions',label:'Consignes',type:'textarea'},{key:'durationMinutes',label:'Durée',type:'number'},{key:'responseRequired',label:'Réponse obligatoire',type:'checkbox'}]},
FILE_SUBMISSION:{type:'FILE_SUBMISSION',label:'Remise de fichier',icon:'⇧',category:'interaction',description:'Demande au participant de remettre un document ou un travail.',defaultVisibility:'BOTH',defaultContent:{instructions:'',acceptedTypes:'.pdf,.doc,.docx,.ppt,.pptx,.jpg,.png',maxFiles:1},capabilities:cap(true,true),status:'foundation',fields:[{key:'instructions',label:'Travail à remettre',type:'textarea'},{key:'acceptedTypes',label:'Formats acceptés',type:'text'},{key:'maxFiles',label:'Nombre maximum de fichiers',type:'number'}]},
TRAINER_NOTE:{type:'TRAINER_NOTE',label:'Notes formateur',icon:'✎',category:'facilitation',description:'Repère privé pour le formateur.',defaultVisibility:'TRAINER',defaultContent:{note:'',cue:''},capabilities:cap(true,false,false,true),status:'active'},
BREAK:{type:'BREAK',label:'Pause',icon:'Ⅱ',category:'facilitation',description:'Insère une pause dans le déroulement.',defaultVisibility:'BOTH',defaultContent:{message:'',instructions:''},capabilities:cap(true,true),status:'active'},
TIMER:{type:'TIMER',label:'Minuteur',icon:'◷',category:'facilitation',description:'Affiche un compte à rebours synchronisé pendant une activité.',defaultVisibility:'LIVE',defaultContent:{minutes:5,label:'Temps restant',visibleToLearners:true,autoContinue:false},capabilities:cap(true,false),status:'foundation',fields:[{key:'minutes',label:'Durée (minutes)',type:'number'},{key:'label',label:'Libellé',type:'text'},{key:'visibleToLearners',label:'Visible aux participants',type:'checkbox'},{key:'autoContinue',label:'Passer automatiquement au bloc suivant',type:'checkbox'}]},
WHITEBOARD:{type:'WHITEBOARD',label:'Tableau blanc',icon:'□',category:'collaboration',description:'Tableau pédagogique formateur ou collaboratif.',defaultVisibility:'LIVE',defaultContent:{instructions:'',mode:'TRAINER_ONLY',template:'BLANK'},capabilities:cap(true,false,true),status:'foundation',fields:[{key:'instructions',label:'Consignes',type:'textarea',placeholder:'Ce que les participants doivent faire sur le tableau…'},{key:'mode',label:'Mode',type:'select',options:options([['TRAINER_ONLY','Formateur seulement'],['COLLABORATIVE','Collaboratif']])},{key:'template',label:'Fond de départ',type:'select',options:options([['BLANK','Tableau vide'],['PREPARED','Tableau préparé']])}]},
INTERACTIVE_BOOK:{type:'INTERACTIVE_BOOK',label:'Livre interactif',icon:'▤',category:'content',description:'Manuel interactif annotable et synchronisable pendant la formation.',defaultVisibility:'BOTH',defaultContent:{resourceId:'',instructions:'',startPage:1,syncPage:true,allowLearnerAnnotations:false},capabilities:cap(true,true,true),status:'foundation',fields:[{key:'resourceId',label:'Manuel / ressource',type:'text',placeholder:'Ressource importée'},{key:'instructions',label:'Consignes',type:'textarea'},{key:'startPage',label:'Page de départ',type:'number'},{key:'syncPage',label:'Synchroniser la page du formateur',type:'checkbox'},{key:'allowLearnerAnnotations',label:'Autoriser les annotations des participants',type:'checkbox'}]}
};

export const TRAINING_TOOL_TYPES=Object.keys(TRAINING_TOOLS) as TrainingToolType[];
export const TRAINING_TOOL_PALETTE=TRAINING_TOOL_TYPES.map(type=>TRAINING_TOOLS[type]);
export const TRAINING_TOOL_CATEGORIES:TrainingToolCategory[]=['structure','content','interaction','collaboration','facilitation'];
export const getTrainingTool=(type:TrainingToolType)=>TRAINING_TOOLS[type];
export const getTrainingToolsForDelivery=(delivery:'LIVE'|'SELF_PACED'|'BOTH')=>TRAINING_TOOL_PALETTE.filter(tool=>delivery==='BOTH'?(tool.capabilities.live||tool.capabilities.selfPaced):delivery==='LIVE'?tool.capabilities.live:tool.capabilities.selfPaced);
const cloneContent=(content:Record<string,unknown>)=>JSON.parse(JSON.stringify(content)) as Record<string,unknown>;
export const createTrainingToolBlock=(type:TrainingToolType):TrainingToolBlock=>{const tool=getTrainingTool(type);return {type,title:tool.label,content:cloneContent(tool.defaultContent),durationMinutes:null,visibility:tool.defaultVisibility};};
export const hydrateTrainingToolBlock=(block:TrainingToolBlock):TrainingToolBlock=>{const tool=getTrainingTool(block.type);return {...block,title:block.title||tool.label,content:{...cloneContent(tool.defaultContent),...(block.content||{})},visibility:block.visibility||tool.defaultVisibility};};
