import {NextResponse} from 'next/server';
import {getCloudflareContext} from '@opennextjs/cloudflare';

type WorkersAI={run:(model:string,input:Record<string,unknown>)=>Promise<any>};
type Env={AI?:WorkersAI};
const TYPES=['SECTION','TEXT','IMAGE','VIDEO','ACTIVITY','SCENARIO','LIVE_QUESTION','DISCUSSION','TRAINER_NOTE','BREAK'];

function extractJSON(text:string){const clean=text.replace(/```json|```/gi,'').trim();const start=clean.indexOf('{');const end=clean.lastIndexOf('}');if(start<0||end<start)throw new Error('La réponse IA ne contient pas de JSON valide.');return JSON.parse(clean.slice(start,end+1));}

export async function POST(request:Request){try{
 const body=await request.json();const topic=String(body.topic||'').trim();const audience=String(body.audience||'').trim();const objective=String(body.objective||'').trim();const duration=Math.max(10,Math.min(480,Number(body.duration)||60));const delivery=['LIVE','SELF_PACED','BOTH'].includes(body.delivery)?body.delivery:'BOTH';
 if(!topic)return NextResponse.json({error:'Indique le sujet de la formation.'},{status:400});
 const{env}=getCloudflareContext();const ai=(env as unknown as Env).AI;if(!ai)return NextResponse.json({error:'Workers AI n’est pas disponible.'},{status:500});
 const system=`Tu es ÉVOOT AI, concepteur pédagogique professionnel pour entreprises et organisations. Tu crées des brouillons de formations concrètes, engageantes et directement utilisables. Tu dois retourner UNIQUEMENT un objet JSON valide, sans markdown ni commentaire.\nStructure exacte: {"title":"...","description":"...","blocks":[{"type":"SECTION|TEXT|IMAGE|VIDEO|ACTIVITY|SCENARIO|LIVE_QUESTION|DISCUSSION|TRAINER_NOTE|BREAK","title":"...","content":{},"durationMinutes":5,"visibility":"LIVE|SELF_PACED|BOTH|TRAINER"}]}.\nUtilise seulement ces types: ${TYPES.join(', ')}. La somme des durationMinutes doit être proche de la durée demandée. Commence par une introduction et termine par une synthèse/conclusion. Varie les blocs selon le sujet et le mode. N’ajoute IMAGE ou VIDEO que si cela apporte une vraie valeur; laisse alors url vide. TRAINER_NOTE doit être visibility TRAINER. Pour SECTION content={"intro":"...","objective":"..."}. TEXT={"text":"...","keyPoint":"..."}. IMAGE={"url":"","caption":"...","alt":"..."}. VIDEO={"url":"","intro":"...","instructions":"..."}. ACTIVITY={"objective":"...","instructions":"...","materials":"...","debrief":"..."}. SCENARIO={"context":"...","situation":"...","task":"...","debrief":"..."}. LIVE_QUESTION={"prompt":"...","answers":["...","...","...","..."],"why":"...","relances":["...","...","..."]}. DISCUSSION={"prompt":"...","relances":["...","...","..."],"takeaway":"..."}. TRAINER_NOTE={"note":"...","cue":"..."}. BREAK={"message":"...","instructions":"..."}. Écris un contenu substantiel, professionnel, clair et pratique. Les scénarios doivent être réalistes. Les questions servent à faire réfléchir et discuter, pas à humilier ou piéger. Ne fais aucun diagnostic et ne transforme pas une formation professionnelle en psychothérapie.`;
 const user=`Crée une formation complète. Sujet: ${topic}\nPublic cible: ${audience||'professionnels en entreprise'}\nObjectif: ${objective||'développer des compétences concrètes et applicables'}\nDurée: ${duration} minutes\nMode: ${delivery}.`;
 const result=await ai.run('@cf/google/gemma-4-26b-a4b-it',{messages:[{role:'system',content:system},{role:'user',content:user}],max_tokens:7000,chat_template_kwargs:{enable_thinking:false}});
 const text=typeof result?.response==='string'?result.response:result?.choices?.[0]?.message?.content;if(!text)throw new Error('Aucun contenu généré.');const parsed=extractJSON(text);
 if(!Array.isArray(parsed.blocks))throw new Error('Le scénario généré est incomplet.');parsed.blocks=parsed.blocks.filter((b:any)=>TYPES.includes(b.type)).map((b:any)=>({type:b.type,title:String(b.title||b.type),content:b.content&&typeof b.content==='object'?b.content:{},durationMinutes:Number.isFinite(Number(b.durationMinutes))?Number(b.durationMinutes):null,visibility:['LIVE','SELF_PACED','BOTH','TRAINER'].includes(b.visibility)?b.visibility:(b.type==='TRAINER_NOTE'?'TRAINER':'BOTH')}));
 return NextResponse.json({training:parsed});
 }catch(error){const message=error instanceof Error?error.message:'Erreur inconnue';return NextResponse.json({error:`ÉVOOT AI n’a pas pu créer la formation: ${message}`},{status:500});}}
