'use client';
import {useEffect,useState} from 'react';
type Block={id:number;type:'text'|'image'|'video'|'question';title:string;content:string;media?:string};
const KEY='evoot-training-draft';
export default function TrainingBuilder(){
 const [title,setTitle]=useState('Nouvelle formation'); const [description,setDescription]=useState(''); const [saved,setSaved]=useState(false); const [preview,setPreview]=useState(false);
 const [blocks,setBlocks]=useState<Block[]>([{id:1,type:'text',title:'Introduction',content:''}]);
 useEffect(()=>{try{const raw=localStorage.getItem(KEY);if(raw){const d=JSON.parse(raw);setTitle(d.title||title);setDescription(d.description||'');setBlocks(d.blocks||blocks)}}catch{}},[]);
 const add=(type:Block['type'])=>setBlocks(v=>[...v,{id:Date.now(),type,title:type==='image'?'Image':type==='video'?'Vidéo':type==='question'?'Question ÉVOOT':'Texte',content:''}]);
 const save=()=>{localStorage.setItem(KEY,JSON.stringify({title,description,blocks,updatedAt:new Date().toISOString()}));setSaved(true);setTimeout(()=>setSaved(false),1800)};
 const update=(id:number,patch:Partial<Block>)=>setBlocks(v=>v.map(b=>b.id===id?{...b,...patch}:b));
 const remove=(id:number)=>setBlocks(v=>v.filter(b=>b.id!==id));
 const media=(id:number,file?:File)=>{if(!file)return;const r=new FileReader();r.onload=()=>update(id,{media:String(r.result)});r.readAsDataURL(file)};
 if(preview)return <main className="previewPage"><button className="secondary" onClick={()=>setPreview(false)}>← Retour à l’éditeur</button><div className="previewTraining"><div className="eyebrow">APERÇU PARTICIPANT</div><h1>{title}</h1><p>{description}</p>{blocks.map(b=><section key={b.id} className="previewBlock"><small>{b.type.toUpperCase()}</small><h2>{b.title}</h2>{b.type==='image'&&b.media&&<img src={b.media} alt=""/>}{b.type==='video'&&b.media&&<video src={b.media} controls/>}{b.content&&<p>{b.content}</p>}</section>)}</div></main>;
 return <><div className="builderActions"><button className="secondary" onClick={()=>setPreview(true)}>Aperçu</button><button className="primary" onClick={save}>{saved?'✓ Enregistré':'Enregistrer'}</button></div><div className="builderWorkspace"><aside className="builderTools"><small>AJOUTER</small><button onClick={()=>add('text')}>T <span>Texte</span></button><button onClick={()=>add('image')}>▧ <span>Photo / image</span></button><button onClick={()=>add('video')}>▶ <span>Vidéo</span></button><button onClick={()=>add('question')}>? <span>Question ÉVOOT</span></button></aside><section className="builderCanvas"><div className="builderTitle"><div><div className="eyebrow">FORMATION</div><input value={title} onChange={e=>setTitle(e.target.value)}/><textarea placeholder="Objectif de la formation…" value={description} onChange={e=>setDescription(e.target.value)}/></div></div><div className="timelineLabel">CONTENU</div>{blocks.map((b,i)=><article className="contentBlock" key={b.id}><div className="contentNumber">{String(i+1).padStart(2,'0')}</div><div className="contentEdit"><small>{b.type.toUpperCase()}</small><input value={b.title} onChange={e=>update(b.id,{title:e.target.value})}/>{b.type==='text'&&<textarea placeholder="Contenu…" value={b.content} onChange={e=>update(b.id,{content:e.target.value})}/>} {b.type==='image'&&<label className="mediaDrop"><input type="file" accept="image/*" onChange={e=>media(b.id,e.target.files?.[0])}/>{b.media?<img src={b.media} alt="aperçu"/>:<><span>＋</span><strong>Ajouter une photo</strong></>}</label>}{b.type==='video'&&<><label className="mediaDrop"><input type="file" accept="video/*" onChange={e=>media(b.id,e.target.files?.[0])}/>{b.media?<video src={b.media} controls/>:<><span>▶</span><strong>Ajouter une vidéo</strong></>}</label><input className="urlInput" placeholder="ou lien vidéo" value={b.content} onChange={e=>update(b.id,{content:e.target.value})}/></>}{b.type==='question'&&<textarea placeholder="Écris la question ou le scénario…" value={b.content} onChange={e=>update(b.id,{content:e.target.value})}/>}</div><button className="blockMenu" onClick={()=>remove(b.id)}>×</button></article>)}<div className="quickAdd"><span>Ajouter :</span><button onClick={()=>add('text')}>Texte</button><button onClick={()=>add('image')}>Photo</button><button onClick={()=>add('video')}>Vidéo</button><button onClick={()=>add('question')}>Question</button></div></section></div></>;
}
