'use client';
import {FormEvent,useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import '../portals.css';

export default function LoginPage(){
 const router=useRouter();const[email,setEmail]=useState('');const[code,setCode]=useState('');const[step,setStep]=useState<'EMAIL'|'CODE'>('EMAIL');const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');
 useEffect(()=>{const error=new URLSearchParams(window.location.search).get('error');if(error)setMessage('Le lien est invalide ou expiré. Demande un nouveau code.');},[]);
 async function requestCode(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');try{const r=await fetch('/api/auth/login/request',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Impossible d’envoyer le code');setStep('CODE');setMessage('Regarde tes courriels : ton code EVOOT! est en route.');}catch(err){setMessage(err instanceof Error?err.message:'Erreur');}finally{setBusy(false)}}
 async function verify(e:FormEvent){e.preventDefault();if(code.length!==6)return;setBusy(true);setMessage('');try{const r=await fetch('/api/auth/login/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,code})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Code invalide');router.replace(d.destination||'/learner');}catch(err){setMessage(err instanceof Error?err.message:'Erreur');}finally{setBusy(false)}}
 return <main className="portalPage"><header className="portalTop"><Link href="/" className="brand">ÉV<span>OO</span>T!</Link><Link href="/">← Accueil</Link></header><section className="portalHero" style={{maxWidth:620,margin:'70px auto 0'}}><div className="eyebrow">CONNEXION SÉCURISÉE</div><h1>{step==='EMAIL'?'Entre ton adresse courriel.':'Entre ton code.'}</h1><p>{step==='EMAIL'?'EVOOT reconnaît ton rôle et t’envoie automatiquement dans le bon portail. Aucun mot de passe à retenir.':<>Un code à 6 chiffres a été envoyé à <b>{email}</b>.</>}</p><form onSubmit={step==='EMAIL'?requestCode:verify} style={{display:'grid',gap:14,marginTop:28}}>{step==='EMAIL'?<input type="email" required autoFocus autoComplete="email" placeholder="nom@entreprise.ca" value={email} onChange={e=>setEmail(e.target.value)} style={{fontSize:18,padding:16,borderRadius:10}}/>:<input type="text" required autoFocus inputMode="numeric" autoComplete="one-time-code" maxLength={6} placeholder="000000" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} style={{fontSize:32,letterSpacing:10,textAlign:'center',padding:16,borderRadius:10}}/>}<button className="primary" disabled={busy||(step==='CODE'&&code.length!==6)}>{busy?'Un instant…':step==='EMAIL'?'Recevoir mon code':'Me connecter'}</button></form>{message&&<p style={{marginTop:18}}>{message}</p>}{step==='CODE'&&<button className="ghost" style={{marginTop:12}} onClick={()=>{setStep('EMAIL');setCode('');setMessage('')}}>Changer d’adresse courriel</button>}<p style={{marginTop:28,opacity:.7}}>Le code expire après 15 minutes et ne fonctionne qu’une seule fois.</p></section></main>}
