import {NextResponse} from 'next/server';
import {VIRTUAL_CLASSROOM_LIMITS,classroomCapacity} from '@/lib/classroom-limits';
import {getAuthContext} from '@/lib/auth';
import {getDB} from '@/lib/db';

type Member={id:string;userId:number;displayName:string;role:'trainer'|'learner';sessionId:string;tracks:Array<{trackName:string;kind:string}>;updatedAt:number};
const rooms=new Map<string,Map<string,Member>>();const TTL=1000*60*5;
function clean(room:Map<string,Member>){const now=Date.now();for(const [id,m] of room)if(now-m.updatedAt>TTL)room.delete(id)}
async function authorize(roomId:string){const auth=await getAuthContext();if(!auth?.organizationId)return null;const courseSessionId=Number(roomId);if(!courseSessionId)return null;const db=getDB();const session=await db.prepare(`SELECT id FROM course_sessions WHERE id=? AND organization_id=?`).bind(courseSessionId,auth.organizationId).first();if(!session)return null;const isTrainer=auth.roles.includes('TRAINER')||auth.roles.includes('ORG_ADMIN');if(isTrainer)return{auth,role:'trainer' as const};const enrolled=await db.prepare(`SELECT e.id FROM enrollments e WHERE e.organization_id=? AND e.user_id=? AND e.status='ACTIVE' AND (e.course_session_id=? OR (e.course_session_id IS NULL AND e.training_id=(SELECT training_id FROM course_sessions WHERE id=? AND organization_id=?))) LIMIT 1`).bind(auth.organizationId,auth.userId,courseSessionId,courseSessionId,auth.organizationId).first();return enrolled?{auth,role:'learner' as const}:null}
export async function GET(req:Request){const roomId=new URL(req.url).searchParams.get('roomId')||'';const access=await authorize(roomId);if(!access)return NextResponse.json({error:'Non autorisé'},{status:401});const room=rooms.get(roomId)||new Map<string,Member>();clean(room);rooms.set(roomId,room);return NextResponse.json({members:[...room.values()].map(({userId,...m})=>m),capacity:classroomCapacity(room.size),maxVisibleVideos:VIRTUAL_CLASSROOM_LIMITS.maxVisibleVideos})}
export async function POST(req:Request){try{const b=await req.json() as {roomId?:string;sessionId?:string;tracks?:Array<{trackName:string;kind:string}>};if(!b.roomId||!b.sessionId)return NextResponse.json({error:'roomId and sessionId required'},{status:400});const access=await authorize(b.roomId);if(!access)return NextResponse.json({error:'Non autorisé'},{status:401});const id=`user-${access.auth.userId}`,room=rooms.get(b.roomId)||new Map<string,Member>();clean(room);if(!room.has(id)&&room.size>=VIRTUAL_CLASSROOM_LIMITS.maxParticipants)return NextResponse.json({error:'CLASSROOM_FULL',message:`Cette classe virtuelle a atteint sa capacité de ${VIRTUAL_CLASSROOM_LIMITS.maxParticipants} personnes.`,capacity:classroomCapacity(room.size)},{status:409});room.set(id,{id,userId:access.auth.userId,displayName:access.auth.displayName,role:access.role,sessionId:b.sessionId,tracks:b.tracks||[],updatedAt:Date.now()});rooms.set(b.roomId,room);return NextResponse.json({ok:true,members:[...room.values()].map(({userId,...m})=>m),capacity:classroomCapacity(room.size),maxVisibleVideos:VIRTUAL_CLASSROOM_LIMITS.maxVisibleVideos})}catch{return NextResponse.json({error:'Invalid room presence'},{status:400})}}
export async function DELETE(req:Request){const roomId=new URL(req.url).searchParams.get('roomId')||'',access=await authorize(roomId);if(!access)return NextResponse.json({error:'Non autorisé'},{status:401});rooms.get(roomId)?.delete(`user-${access.auth.userId}`);return NextResponse.json({ok:true})}
