import {NextResponse} from 'next/server';
import {VIRTUAL_CLASSROOM_LIMITS,classroomCapacity} from '@/lib/classroom-limits';

type Member={id:string;role:'trainer'|'learner';sessionId:string;tracks:Array<{trackName:string;kind:string}>;updatedAt:number};
const rooms=new Map<string,Map<string,Member>>();
const TTL=1000*60*60*4;
function clean(room:Map<string,Member>){const now=Date.now();for(const [id,m] of room)if(now-m.updatedAt>TTL)room.delete(id)}
export async function GET(req:Request){const u=new URL(req.url),roomId=u.searchParams.get('roomId')||'demo';const room=rooms.get(roomId)||new Map<string,Member>();clean(room);rooms.set(roomId,room);return NextResponse.json({members:[...room.values()],capacity:classroomCapacity(room.size),maxVisibleVideos:VIRTUAL_CLASSROOM_LIMITS.maxVisibleVideos})}
export async function POST(req:Request){try{const b=await req.json() as {roomId?:string;id?:string;role?:'trainer'|'learner';sessionId?:string;tracks?:Array<{trackName:string;kind:string}>};if(!b.roomId||!b.id||!b.sessionId)return NextResponse.json({error:'roomId, id and sessionId required'},{status:400});const room=rooms.get(b.roomId)||new Map<string,Member>();clean(room);if(!room.has(b.id)&&room.size>=VIRTUAL_CLASSROOM_LIMITS.maxParticipants)return NextResponse.json({error:'CLASSROOM_FULL',message:`Cette classe virtuelle a atteint sa capacité de ${VIRTUAL_CLASSROOM_LIMITS.maxParticipants} personnes.`,capacity:classroomCapacity(room.size)},{status:409});room.set(b.id,{id:b.id,role:b.role||'learner',sessionId:b.sessionId,tracks:b.tracks||[],updatedAt:Date.now()});rooms.set(b.roomId,room);return NextResponse.json({ok:true,members:[...room.values()],capacity:classroomCapacity(room.size),maxVisibleVideos:VIRTUAL_CLASSROOM_LIMITS.maxVisibleVideos})}catch{return NextResponse.json({error:'Invalid room presence'},{status:400})}}
export async function DELETE(req:Request){const u=new URL(req.url),roomId=u.searchParams.get('roomId')||'',id=u.searchParams.get('id')||'';rooms.get(roomId)?.delete(id);return NextResponse.json({ok:true})}
